### ISSUE TITLE
error of no matching DALI plugin

### ISSUE THREAD

**Issue by Haoyulance** [NVIDIA/DALI#1065]
I used this command
```
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali
```
to install DALI and it works very well. But when I want to 
```
import nvidia.dali.plugin.tf
```
I got this error 
```
1.8.0
Traceback (most recent call last):
  File "/home/lhy/experiment/experiment.py", line 6, in <module>
    import nvidia.dali.plugin.tf
  File "/home/lhy/anaconda2/envs/tf-1.8-cp3/lib/python3.6/site-packages/nvidia/dali/plugin/tf.py", line 35, in <module>
    raise Exception('No matching DALI plugin found for installed TensorFlow version')
Exception: No matching DALI plugin found for installed TensorFlow version
```
I printed the tensorflow-gpu version which is 1.8.0 and CUDA 10.1, but I don't know why I got this error. Need some help.

**Comment by JanuszL** [comment]
Hi,
I'm bit confused - because TensorFlow 1.8 supports only CUDA 9 and when you try to import it from python you will get:
```
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
```
One thing you have missed you haven't installed DALI TensorFlow pluging package.
Please issue the command provided in the documentation - https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/installation.html#id1:
```
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali-tf-plugin
```
When using clean env from the Docker image it works as expected (TensorFlow 1.13.1 and CUDA 10):
```
nvidia-docker run --rm -ti nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
```
Then inside the container:
```
apt-get update && apt-get install -y curl python &&   curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py && pip install tensorflow-gpu==1.13.1 && pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali && pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali-tf-plugin
python -c "import nvidia.dali.plugin.tf"
```

**Comment by Haoyulance** [comment]
Thank you so much! I found it really uses cuda 9 on the linux, that's the reason causing matching problem. I reinstalled the corresponding version of DALI and it works now!
