### ISSUE TITLE
Wrong JPEG library version: library is 90, caller expects 80

### ISSUE THREAD

**Issue by guanfuchen** [NVIDIA/DALI#1073]
get error RuntimeError: Critical error in pipeline: Error in thread 0: [/root/dali/dali/pipeline/operators/decoder/host_decoder.cc:40] [/root/dali/dali/image/jpeg.cc:127] Assert on "jpeg::GetImageInfo(encoded_buffer, length, &width, &height, &components) == true" failed

**Comment by JanuszL** [comment]
Hi,
It seems that some debug warring string is missing the info about image path. I will add it and let you know the PR.
In the meantime, you can try to bisect which image is causing problems and provide it to use for debugging (maybe the jpeg is corrupted or we are not handling it properly).

**Comment by JanuszL** [comment]
@guanfuchen - I double-checked what we are doing in the code. In [0.10 ](https://github.com/NVIDIA/DALI/blob/v0.10.0/dali/pipeline/operators/decoder/host_decoder.cc#L40) you should get the file name in the error message as well. Please provide the failing file so we reproduce this locally.
In the issue title, you have put `Wrong JPEG library version: library is 90, caller expects 80` - cold you elaborate because the error message you posted in the issue description doesn't correspond to the tile.

**Comment by JanuszL** [comment]
If it still doesn't work please reopen.
