### ISSUE TITLE
half precision in TF

### ISSUE THREAD

**Issue by dheerajsreedhar** [NVIDIA/DALI#1085]
This is a question on how DALI handles half precision in tensorflow.

I am referring to the script  in docs/examples/tensorflow/demo/resnet.py. The script runs perfectly fine with both precision=fp16, fp32 and I can see the throughput improvement with half precision. But where do you specify DALI to output half precision images ? 

the interface to DALI from main script is 

    input_func = lambda: nvutils.image_set(
        train_filenames, batch_size, image_height, image_width,
        training=True, distort_color=distort_color,
        deterministic=deterministic, num_threads=num_preproc_threads,
        dali_cpu=dali_cpu, idx_filenames=train_idx_filenames)

and there is no configuration for output precision.  Does DALI always output 32 bit images  inspite of the precision setting in arguments ?

I am trying to integrate DALI with Tensorflow benchmarks code : https://github.com/tensorflow/benchmarks. I am able to see performance improvement with full precision but I am unable to get it working with half.

Thanks,

**Comment by dheerajsreedhar** [comment]
FYI .. For the tensorflow benchmarks code, I have been able to solve the issue with an explicit call to tf.cast( ) operator at the output of DALI. Changing the output_dype of DALI ops to output_dtype=dali.types.FLOAT16 did not work. I guess this should be a bug ?

**Comment by JanuszL** [comment]
Hi,
DALI is capable of outputting float16 as well, but in our example, it is not supported. What you need to do is:
- add FLOAT16 as an output type in [CropMirrorNormalize](https://github.com/NVIDIA/DALI/blob/master/docs/examples/tensorflow/demo/nvutils/image_processing.py#L96) in the pipeline definition
- change [dype](https://github.com/NVIDIA/DALI/blob/master/docs/examples/tensorflow/demo/nvutils/image_processing.py#L159) for float16 in DALI TensorFlow plugin
From DALI point of view, it won't make any performance difference as it doesn't change a way how DALI performs computations, for TensorFlow itself it should have a minor impact as well (if any).
I just noticed that float16 is improperly handled by TensorFlow plugin - it should be fixed by https://github.com/NVIDIA/DALI/pull/1086.
