### ISSUE TITLE
Call for support to CUDA 8.0 and support environment without libjpeg-turbo or nvjpeg

### ISSUE THREAD

**Issue by gzygzy9211** [NVIDIA/DALI#11]
There are 2 reasons.

1) Our training environments are still CUDA 8.0 and it may take too much effort to upgrade all training tools to CUDA 9.0 until new machines are deployed.

2) Since image decoding can hardly be the bottleneck of the whole training pipeline, so image decoding via OpenCV is sufficient for most scenarios. Less dependency make DALI easier to be used in existing training environment.

**Comment by JanuszL** [comment]
Hi,
1) Technically it is possible to backport for CUDA 8.0. In the long term we are focusing on support CUDA 9.0 and versions which are above it. We are not planning to do that, but we are open to any pull request with such change.
2) Currently we are focusing on fully utilize GPU capabilities (jpeg decoding offloading as well), still your suggestion is accurate. We will add it as another point in our ToDo list.

**Comment by ptrendx** [comment]
About point 2 - this is a common misconception that decoding images is negligible and other augmentations like resize etc. take the most time. That is actually not true - decoding, even for relatively small images like 480p, takes as much time as resize (and with tricks like backprojected crop, where you resize only the fragment that would be further cropped, it is actually slower than resize). 

OpenCV, technically can use libjpeg-turbo if you have it in the system, although only for OpenCV 3.0+, which is not the default OpenCV package for Ubunutu 16.04 and below. If you install OpenCV via a package manager on Ubuntu 16.04 you will get OpenCV 2, which comes bundled with its own libjpeg (non-turbo) and is significantly slower. Anyway, even if you have OpenCV 3 and libjpeg-turbo installed, cv::imdecode is still slower than calling TurboJPEG API (I guess they are doing additional memcpy somewhere, but I did not inspect OpenCV code to be sure).

The goal of DALI is to ease getting good performance out of the input pipeline, and while I agree that having less dependencies seems like a good thing, having multiple options, some of which are bad from the performance perspective, is confusing. Especially since the pip package comes with proper versions of those dependencies (like OpenCV, nvJPEG and libjpeg-turbo) bundled.

**Comment by gzygzy9211** [comment]
@ptrendx In 2) what I mean is make nvJPEG and libjpeg-turbo to be OPTIONALL rather than required. And actually it is very easy to do that in current DALI implementation. 

And according to my experience, in many training scenarios augmentation is a combination of geometry transform, pixel-wise processing and type conversion and maybe some other operations, whose time consuming is usually larger than image decoding. Besides, most augmentation operation can easily benefit from GPU while it is harder for image decoding. 

So I think my suggestion is reasonable, and still, GPU decoding is recommended in DALI and enabled by default.
