### ISSUE TITLE
Error loading images with ops.FileReader random shuffle

### ISSUE THREAD

**Issue by haoxintong** [NVIDIA/DALI#1116]
Hi, 
I am using FileReader to load my images as following:

- Data: 100 images each with its own label in filelist.txt, I use the label as the image index.
- 8 pipeline instance for 8 GPUs, batch size 1, parameter setting of FileReader:
    - num_shards: 8
    - shard_id: id of gpu, [0, ... ,7]
    - random_shuffle=True
    - seed=12
- In define_graph , I get the idx of image by `_, idx = self.reader()`
- Iterator:
```python
iter = DALIGenericIterator(pipes, [("idx", "label")],
                             size=100, auto_reset=True, dynamic_shape=True)
```

Then I found only 72 of the total 100 idx can be observed in an epoch.
When I change the parameter `random_shuffle` to False, I can get all images in my dataset.

Is there something wrong of my usage?

**Comment by awolant** [comment]
Hi, thanks for the question. If I understand correctly, during an epoch you are getting some images multiple times and some other never, right? And with random shuffling turned off, everything is fine?
If so, this is due to the old implementation of random shuffling in DALI. We reworked it recently to change this behavior in #1005 It was merged yesterday.
Maybe you can try to build DALI from source and see if it helps or wait for the nightly build to be ready to try it out?

**Comment by haoxintong** [comment]
Thanks, I will rebuild and have a try.
