### ISSUE TITLE
Can I get the image paths when I use FileReader 

### ISSUE THREAD

**Issue by kgl-prml** [NVIDIA/DALI#1170]
When I use FileReader to read images in a directory, could I get the path of the images?

**Comment by awolant** [comment]
Hi, thanks for the question. There is no support for this via `FileReader` op right now, but you can still accomplish it using [ExternalSource](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html). Exact info on how to do this you can find in #1130

**Comment by kgl-prml** [comment]
OK, thank you.

> Hi, thanks for the question. There is no support for this via `FileReader` op right now, but you can still accomplish it using [ExternalSource](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html). Exact info on how to do this you can find in #1130

**Comment by snu-ceyda** [comment]
I'm trying do the same thing I'm passing the image path through an `ExternalSource` op. But I get the error ` Cannot create type for unknown format string`. I know this is because TensorCPU doesn't support string data format but i was wondering if there is a work around for this (without having to do string->numeric->string conversion)? I don't need this value as a tensor so is there a way to pass values to pytorch DALIGenericIterator without casting to TensorCPU and maybe using another [type](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/data_types.html?highlight=types) supporting strings?

**Comment by JanuszL** [comment]
@snu-ceyda - sorry, but DALI supports TensorCPU/TensorGPU as its fundamental type. Other data types are not supported. What you can do it create a dict int->string at python level and just pass this one value int as an additional label that you would map back when needed at the end of the DALI pipeline.

**Comment by JanuszL** [comment]
Now it is possible to obtain it using [the `source_info` method of DALI tensor](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/data_types.html#nvidia.dali.backend.TensorGPU.source_info), in most cases it should be propagated from the reader.
