### ISSUE TITLE
can't override __next__ in  GenericIterator

### ISSUE THREAD

**Issue by makslevental** [NVIDIA/DALI#1227]
```python

class DALICHWIterator(DALIGenericIterator):
    def __init__(self, *args, **kwargs):
        super(DALICHWIterator, self).__init__(*args, **kwargs)

    def __next__(self):
        n = super(DALICHWIterator, self).__next__()
        n[0]["lr_image"] = n[0]["lr_image"].permute(0, 3, 1, 2)
        n[0]["hr_image"] = n[0]["hr_image"].permute(0, 3, 1, 2)
        return n


class DALILRHRIterator(DALICHWIterator):
    def __init__(self, *args, **kwargs):
        super(DALILRHRIterator, self).__init__(*args, **kwargs)

    def __next__(self):
        n = super(DALILRHRIterator, self).__next__()
        lr_image, hr_image = n[0]["lr_image"], n[0]["hr_image"]
        return lr_image, hr_image
```

chokes because of https://github.com/NVIDIA/DALI/blob/master/dali/python/nvidia/dali/plugin/pytorch.py#L138

**Comment by awolant** [comment]
Hello, thanks for the question.
[Code you linked](https://github.com/NVIDIA/DALI/blob/master/dali/python/nvidia/dali/plugin/pytorch.py#L138) is there as a part of prefetching mechanism of this loader. As yo pointed out, code like yours will not work.
You could do something like this by wrapping `DALIGenericIterator` instead of subclassing it, I think. Or you can do some kind of decorator?
