### ISSUE TITLE
How is WarpAffine supposed to be used?

### ISSUE THREAD

**Issue by vahidk** [NVIDIA/DALI#1404]
I'm trying to use the WarpAffine op. It seems like it only supports constant transformation matrix which is almost never what you want to do. How can I use WarpAffine with dynamic matrices?
I tried generating and feeding matrices through ExternalSource but am getting the following error:
"failed: Argument input may only be produced by support op."
What is a support op? Searching for "support op" on docs shows zero results. Can you provide an example usage of WarpAffine?

**Comment by JanuszL** [comment]
Hi,
Yes in the most recent release the WarpAffine operator is limited. However, it is under heavy rework and thanks to https://github.com/NVIDIA/DALI/pull/1390 or https://github.com/NVIDIA/DALI/pull/1387 it should be possible to do exactly what you are asking for.
SO stay tuned and check our nightly builds.
@mzient anything to add?

**Comment by mzient** [comment]
It's been released in 0.16. Now the matrices can be provided as tensor arguments (`matrix = <cpu_op_output>`) or even as a second regular input, In the latter case, the matrices can be passed in GPU memory. You can also specify output sizes (constant or per-sample) and use clamp-to-edge instead of constant fill color.
Refer to the example for details:
https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/examples/warp.html
