### ISSUE TITLE
Does ops.ExternalSource operator has support for sharding ? 

### ISSUE THREAD

**Issue by cristyioan2000** [NVIDIA/DALI#1457]
I want to read and augment data that consists of **bounding boxes** as labels and **images**. I want to make this process as fast as possible for training on multiple GPUs. Can ExternalSource operator, use sharding ? If no, these operations from the list bellow, are the only one that support sharding ?

- CocoReader

- FileReader( Can I read bounding boxes labels with
FileReader ?  )

**Comment by JanuszL** [comment]
Hi,
Sharding is supported by all readers:
- COCOReader
- CaffeReader
- Caffe2Reader
- FileReader
- MXNetReader
- SequenceReader
- TFRecordReader
- VideoReader

COCO reader seems like a good choice to convert your data to, however, you can keep it in TFRecord format as well. Other containers maybe not a good choice to keep this kind of that inside (some may not that ability at all like caffe LMDB, in some cases DALI may not support all possible flavor of the given format like RecordIO).

ExternalReader may be a good start due to easy prototyping in python, but as it involves a lot of python code invocations and additional, synchronous copy of data it will be slower compared to other readers. Regarding sharding, ExternalReader juts accepts a batch of data each iteration so it is up to the user to figure out how to provide it including shuffling and sharding. You may want to look into [that example](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html).
