### ISSUE TITLE
pytorch-external_input.ipynb

### ISSUE THREAD

**Issue by justinblaber** [NVIDIA/DALI#1604]
Is this up to date?

The reason I ask is the following:

```
        if self.i >= self.n:
            raise StopIteration
```

Never gets executed because of:

`            self.i = (self.i + 1) % self.n`

i.e. `self.i` wraps around and never gets larger than `self.n`. This means the data gets shuffled once and not at every epoch.

Is this jupyter notebook still considered the most up to date for an external input? If so, I'll update it, but just wanted to make sure first.

**Comment by JanuszL** [comment]
Hi,
Yes, it is still valid and works fine. It works because `PyTorchIterator` receives `size` and in this cause the epoch to end in this example. However if you change `self.i = (self.i + 1) % self.n` to `self.i = self.i + 1` it still should work.
However, when you put some dummy size into `PyTorchIterator` it won't work.
Do you have any good idea of how `PyTorchIterator` should behave and what kind of API should expose when the data size is not known ahead?

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/1625 should address your case. When FW iterator size is negative the end of iteration relies only on the `StopIteration` raised from the inside of `iter_setup`.

**Comment by JanuszL** [comment]
0.19 is out and should address this. Please reopen if it doesn't work.
