### ISSUE TITLE
Is there a more efficient way for BBoxRotate?

### ISSUE THREAD

**Issue by 00liujj** [NVIDIA/DALI#1628]
I implemented a user defined CPU BBoxRotate for image and use it like this.

    image = ops.Rotate(device="gpu", fill_value=80)(image, angle=angle, mask=rotate)
    boxes = ops.BBoxRotate(device="cpu", ltrb=True)(image, boxes, angle=angle, mask=rotate)

The problem is BBoxRotate will run on CPU, `image` is used for fetch the width and height of the image, and `image` should also on CPU. I hope that `image` is on GPU for efficiency, but it doesn't work.

**Comment by JanuszL** [comment]
It doesn't work because DALI executes first the CPU operators, then Mixed and GPU. In your case `image` is probably not available as you may be using the mixed decoder.
Currently, there is no ideal solution to your case. You can implement `BBoxRotate` for GPU, build your pipeline in a way that `image` is on CPU before calling Rotate, or create some custom raw image shape operator that would extract shapes for encoded images while they are still on the CPU - check https://github.com/NVIDIA/DALI/blob/master/dali/image/image_factory.h and https://github.com/NVIDIA/DALI/blob/master/dali/image/generic_image.h (PeekShapeImpl).

**Comment by 00liujj** [comment]
Thank you for your replay. If I use GPU for `BBoxRotate`, the following ops like `BBoxPaste` and `BBoxCrop`  and `BBoxFlip` should all on GPU. that would introduce more trouble. 

In my opinion, BBoxPaste->BBoxRotate->BBoxCrop->BBoxFlip would be better for a detection pipeline.

**Comment by JanuszL** [comment]
Then creating an operator that extracts image shape from decoded one may be the only way. The backup solution is to extend the COCO reader and return image shapes as well as an option (COCO JSON has this information).

**Comment by 00liujj** [comment]
Thank you very much for your suggestion. I'll try this `extracts image shape from decoded`.
