### ISSUE TITLE
Apply DALI on TensorRT

### ISSUE THREAD

**Issue by e2sh83** [NVIDIA/DALI#17]
Hi, 
I am curious whether DALI can run on TensortRT library or not. Try is not made yet, I wonder it would be possible.

**Comment by cliffwoolley** [comment]
This is closely related to https://github.com/NVIDIA/DALI/issues/9 .  Conceptually this should be possible, though we likely have some usability improvements needed.

**Comment by e2sh83** [comment]
Thanks for your answer. Then does NVIDIA have plan to release any DALI adaptation for TensorRT?

**Comment by cliffwoolley** [comment]
I think it's not so much an "adaptation" as it is that we should provide some examples of how to DALI and TF-TRT would interact.  The issue raised in #9 is that the frozen graph requirement of TF-TRT adds complexity to the story if your graph wasn't originally trained with DALI.  I think it's still possible, but examples are needed; if anything, TF-TRT could be improved here perhaps more readily than DALI.

**Comment by JanuszL** [comment]
Tracked internally in DALI-130

**Comment by PJ7668** [comment]
I am looking for guidance on how to deploy a model trained using DALI to TRTIS (TensorRT Inference Server). I believe it would suffice if the pre-processing part of the DALI pipeline could be serialized as a TensorRT model. I presume the data fetching part of the pipeline would need to be excluded or modified since TRTIS will just be handing the model data directly.

The current thread and this thread (https://github.com/NVIDIA/DALI/issues/1196) seem to be related to my question but I don't see a clear path forward.

Any help is appreciated.

**Comment by JanuszL** [comment]
Hi,
Currently, we don't have clear guidance on how to plug DALI into TRTIS.
What you could do is  to start from extending [image_client](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/python/image_client.py) in Python using this [DALI example](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html). You need to use the ExternalSource operator as the main DALI use case is the training where the set of the training data is fixed and you define it once for the whole run. For inference, you need to dynamically feed the data to the pipeline.
For the [C++ example](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/c%2B%2B/examples/image_client.cc), DALI unofficial C++ API is needed ([like in this example](https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/pipeline_test.cc) if full control over a pipeline is needed).
However, we cannot guarantee you any performance as DALI was not that much optimized for processing small batches and providing small latency.

Regarding serialization of the DALI pipeline, the main problem is that pipeline for training differs from for the inference (training includes augmentation, while for the inference data is only transformed to the format accepted by the network). DALI pipeline can be serialized and saved, but more consideration of how to couple training and inference pipelines with the trained model is still needed.

If you have any good ideas or suggestion we would be more than happy to discuss.

**Comment by PJ7668** [comment]
Thanks for the response. It's helpful just knowing that I wasn't missing something obvious. It sounds like the intended use for now is that any steps that are strictly pre-processing (i.e. non-random steps) in the DALI pipeline should just be re-implemented on the client side or as a custom backend in the case of TRTIS. In my use cases, I'd prefer the latter since it keeps the pre-processing requirements tied to the model itself and off-loads some of the work to the inference engine. I'll let you know if I come up with something useful beyond that.

Thanks!

**Comment by JanuszL** [comment]
@PJ7668 - you still can do the inference preprocessing with DALI, I'm just saying it is not the main use case. In the RN50 example with PyTorch - https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/pytorch/resnet50/pytorch-resnet50.html there are two pipelines - one for the training and one for the inference. The latter can be reused for TRTIS.

**Comment by PJ7668** [comment]
@JanuszL Got it - thanks.

**Comment by szalpal** [comment]
Using DALI with Triton Inference Server (former TRTIS) is possible with [DALI Backend for Triton](https://github.com/triton-inference-server/dali_backend). On the other hand, using DALI with TensorRT is possible is similar fashion, using DALI's C-API. We don't have the specific DALI+TRT example, however DALI Backend shows a good example of usage. Closing.
