### ISSUE TITLE
Extracting subtensor with ops.Slice

### ISSUE THREAD

**Issue by syb0rg** [NVIDIA/DALI#1716]
I am trying to mimic `torch.index_select()` with `ops.Slice()` to sub-sample a video.  Given a video of shape `torch.Size([3, 32, 1024, 1024])` in "CFHW" order, how would I use this operator to trim it to something like `torch.Size([3, 8, 1024, 1024])`?

I tried looking for examples but couldn't find anything relevant. I then experimented through trial and error to make it work, but was unable to.

**Comment by JanuszL** [comment]
Hi,
You can use [DALI slice operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.Slice). In case of DALI VideoReader, we use "FHWC" format, if you want to transform it to "CFHW" you may try to use [Transpose operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.Transpose).
Can you elaborate on why you want to trim the video? If this is always the same samples (not randomly selected one) you want to strip they maybe you can just ask the VideoReader to provide shorter sequences instead of discarding them latter.

**Comment by syb0rg** [comment]
I am using `ops.CropMirrorNormalize()` to achieve the reordering of the dimensions and do some other processing.  This happens before I would perform the slice operation.

For my use case I require both tensors, a longer video sequence and a shorter one sub-sampled from the longer.  I'm hoping to do something like the following:

```
sub_index = torch.Tensor([ 0,  4,  8, 13, 17, 22, 26, 30]).long()
# frames is torch.Size([3, 32, 1024, 1024])
short = torch.index_select(frames, 1, sub_index)
# short is torch.Size([3, 8, 1024, 1024])
return [short, frames]
```

What would the equivalent look like for `ops.Slice()`?

**Comment by JanuszL** [comment]
With the latest nightly build you should be able to do something like:
```
def __init__(...):
        self.slice = ops.Slice(device="gpu", normalized_anchor = False, normalized_shape = False, axes = [0])
        self.anchors = ops.Constant(device="cpu", fdata = [1])
        self.shape = ops.Constant(device="cpu", fdata = [sub_index])
    def define_graph(self):
        short_sequence = self.slice(long_sequence, self.anchors(), self.shape())
```
If you want to provide the value that changes iteration to iteration and may differ sample to  sample you need to use [the ExternalSource operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.ExternalSource) to fee this data instead of `Constant`.

**Comment by syb0rg** [comment]
With nvidia-dali-nightly-0.19.0.dev20200206 I get this error for this line:

```
sub_index = torch.Tensor([0,  4,  8, 13, 17, 22, 26, 30]).long()
self.shape = ops.Constant(device="cpu", fdata=[sub_index]) # error

ValueError: only one element tensors can be converted to Python scalars
```

Did you mean the nightly build tonight would fix this?  Around what time in UTC do the nightly builds kick off out of curiosity?

**Comment by JanuszL** [comment]
@syb0rg - you can put only one value into constant.
Do you want to provide a different value for each sample in the batch or rotate this value iteration to iteration?
In such case create instead of the Constant operator, the ExternalSource operator and feed it with the desired data each iteration.
Something like:
```
def __init__(...):
        self.slice = ops.Slice(device="gpu", normalized_anchor = False, normalized_shape = False, axes = [0])
        self.anchors = ops.ExternalSource(device="cpu")
        self.shape = ops.ExternalSource(device="cpu")
def iter_setup(self):
       self.feed_input(self.anchors, numpy_sub_index)
       self.feed_input(self.shape, numpy_lenght)
```

**Comment by syb0rg** [comment]
The sub_index value would remain the same throughout the iterations.  I can't provide a list for a constant?

Also, I'm not sure I fully understand the role of the anchor and shape parameters even after reading through the documentation a couple times.  Perhaps this is something else that is throwing me off?

**Comment by JanuszL** [comment]
Sorry, I missed that you are using `index_select` which extracts certain frames from the sequence which is different from what Slice does. Slice cuts a part of multidimensional tensor and returns a smaller one (similar to crop). 
Currently, we don't have any functionality what `index_select` does, the slice can only provide you a subset of consecutive frames. If you want to jump into C++ you can take a look into [`ElementExtract` source code](https://github.com/NVIDIA/DALI/blob/master/dali/operators/sequence/element_extract.cc) and do something similar that would not produce a separate output for each frame but will create just another sequence.

**Comment by JanuszL** [comment]
Hi,
With the most recent improvements in DALI you can use [the `element_extract` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.element_extract) and then [`stack`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.stack).
So something like this should work:
```
   video = fn.stack(*fn.element_extract(frames, element_map=[0,  4,  8, 13, 17]))
```

**Comment by JanuszL** [comment]
Also you can use [the `element_extract` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.sequence_rearrange):
```
new_sequence = fn.sequence_rearrange(sequence, new_order=[0,  4,  8, 13, 17])
```
