### ISSUE TITLE
Dali's types.py file is  conflict with python3.6

### ISSUE THREAD

**Issue by hexiaoting** [NVIDIA/DALI#1809]
I want to start jupyter-notebook for dali tutorial in python3.6 venv, But encounter some problem:
# environment:
```
python3.6
> pip show nvidia-dali
Name: nvidia-dali
Version: 0.19.0
Summary: NVIDIA DALI for CUDA 10.0. Git SHA: 6d532d49328979325fa3ae8b5d58be95bab2364f
Home-page: https://github.com/NVIDIA/dali
Author: NVIDIA Corporation
Author-email: UNKNOWN
License: Apache License 2.0
Location: /home/zhibin/qzhong/dl-dev/lib/python3.6/site-packages
Requires: future
Required-by:
(dl-dev) at gpu80 ~
```
# problem:
```
> jupyter-notebook
Error processing line 1 of /home/zhibin/qzhong/dl-dev/lib64/python3.6/site-packages/matplotlib-3.1.1-py3.6-nspkg.pth:

Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/home/zhibin/qzhong/dl-dev/lib/python3.6/site-packages/nvidia/dali/types.py", line 16, in <module>
    from enum import Enum, unique
  File "/usr/lib64/python3.6/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType'
```

# reason:
dali has a types.py file in /home/zhibin/qzhong/dl-dev/lib/python3.6/site-packages/nvidia/dali/types.py
python3.6 has a types.py too:  /usr/lib64/python3.6/types.py
Are they conflict?

And how to solve this problem？

**Comment by JanuszL** [comment]
I'm not able to reproduce this problem with my local setup (Ubuntu 18.04, virtual env, python 3.6.9).
All I was able to learn about this issue is https://stackoverflow.com/questions/43453414/cannot-import-name-mappingproxytype-error-after-importing-functools.
Could you provide a full reproduction that would show this problem, you can refer [to this guide](https://github.com/NVIDIA/DALI#reporting-problems-asking-questions).

**Comment by JanuszL** [comment]
Please reopen when you can share a repro.
