### ISSUE TITLE
How tfrecord reader works for multi GPU sharding

### ISSUE THREAD

**Issue by dorucia** [NVIDIA/DALI#1876]
Hi,

I have a question regarding how tfrecord reader works for multi GPU sharding.

Let's say we have two tfrecord files and corresponding two index files.
The number of data in each file is different, say 10 and 100.

I set data loader like this on PyTorch.
`opt.local_rank` indicates GPU ID and `opt.num_gpus` represents the number of GPUs.

```
data_loader = TFRecordPipeline(tfrecord, tfrecord_idx,
                               batch_size=opt.batch_size,
                               num_threads=opt.num_workers,
                               device_id=opt.local_rank,
                               shard_id=opt.local_rank,
                               num_shards=opt.num_gpus,
                               shuffle=shuffle)
```

My guess of how sharding works is
1. Select an index file for each GPU at uniformly random regardless the number of data in each tfrecord file.
2. Then set random starting point inside the selected tfrecord file.

In the above example, if we have 4 GPUs, 2 GPUs will get data from the first tfrecord file and the other 2 GPUs will get data from the second file.
If we have 2 GPUs, first and second GPU will get data from the first and second tfrecord file, respectively.

Am I correct?

If I am wrong, is there a way to uniformly visit tfrecord files to sample data?

**Comment by JanuszL** [comment]
Hi,
DALI would treat this data as one big file (just in multiple pieces), and split it equally among the GPUs. So if you have 2GPUs, first will read the first file and 45 entries from the second, while the second GPU would read 55 samples from the second file (in the first epoch). If `stick_to_shard` is not set, all GPUs will advance to the next shard each epoch. Otherwise, they will wrap up and reread the same one as in the first epoch.
The index file is just an auxiliary thing that helps GPUs to jump into their shards without parsing the whole dataset.

**Comment by dorucia** [comment]
I see.
It seems like I should balance the number of data in tfrecord file.

Thanks for reply!

**Comment by JanuszL** [comment]
> It seems like I should balance the number of data in tfrecord file.

If you want to have this uniform distribution of files not samples then probably this is a way to do it.
