### ISSUE TITLE
How to crop from an image smaller than the crop size?

### ISSUE THREAD

**Issue by cfzd** [NVIDIA/DALI#1953]
The crop ops (ops.Crop, ops.FastResizeCropMirror, ops.CropMirrorNormalize, etc.)  only support cropping from images larger than crop size. 

For example, I can crop a 400x400 patch from a 500x500 image, but I can't crop a 400x400 patch from a 300x300 image with 0-pad in the invalid pixels, which is commonly used in the data augmentation of segmentation. 

I tried ops.Pad, but it seems can only pad tensors in the bottom right corner.

I want to realize fused random resize and random crop. What's the correct way of doing this kind of crop?

**Comment by jantonguirao** [comment]
Hi @cfzd,

Unfortunately, it is currently not supported to "Crop" to a window larger than the image itself. It has been discussed internally though and it is in our plans to implement it.

The assumption is that by default the smaller image will be centered in the larger canvas, but it could also be placed at a different point within the canvas by controlling the cropping window anchor. Would that suit your use case?

**Comment by cfzd** [comment]
@jantonguirao Thanks for your reply.

The mentioned method could suit my case perfectly. Is it possible that I can contribute to the community? Or are there any references that I can read to get started quickly?

**Comment by jantonguirao** [comment]
@cfzd There is a small guide about contributing to DALI: https://github.com/NVIDIA/DALI/blob/master/CONTRIBUTING.md. Unfortunately, we don't have yet any guides/tutorials available about DALI internals.

There are several tasks that need to be done in order to consider this feature complete. First, we need to adjust the slicing kernels to support padding. In DALI we call kernels (not to be confused with CUDA kernels) to our low-level module that implements a specific data processing transformation and can be reused in several DALI operators. We have two different implementations of our Slice kernel: the basic one and another one that is fused with other processing steps (normalization, channel permutation, mirroring...). Each of those has a CPU and GPU implementation. The fused implementation has already some padding support but it is not complete since it'd only allow padding on the right (or bottom) side, but not on the left (or top) side.

The second step is to adjust our operators that support slicing (e.g. Crop), to lift the error checking that prevents you to feed images smaller than the cropping window size and adjust the logic invoking the slice kernel. We'd probably need to add an optional argument specifying the padding value (typically 0, but we might want to pad with a specific per-channel value).

Lastly, we'd need to add new test cases to cover the new functionality.

The slice kernel code is here: 
https://github.com/NVIDIA/DALI/tree/master/dali/kernels/slice

The operators are here:
https://github.com/NVIDIA/DALI/tree/master/dali/operators/image/crop
https://github.com/NVIDIA/DALI/tree/master/dali/operators/generic/slice 

Test cases are here:
https://github.com/NVIDIA/DALI/blob/master/dali/test/python/test_operator_crop.py
https://github.com/NVIDIA/DALI/blob/master/dali/test/python/test_operator_crop_mirror_normalize.py
https://github.com/NVIDIA/DALI/blob/master/dali/test/python/test_operator_slice.py

Please let us know if you feel like you'd like to contribute to any of those.

**Comment by JanuszL** [comment]
Hi,
Now `slice` and `crop` operators support `out_of_bounds_policy` so it is possible to do what you asked for.
