### ISSUE TITLE
Question: DALI in subprocess for PyTorch

### ISSUE THREAD

**Issue by weberxie** [NVIDIA/DALI#2088]
Hi team,

DALI cpu mode cost two much CPU and it runs in the same process with training process, so how can we run DALI in a separate process like the official practice with PyTorch DataLoader and Dataset？

Thanks!

**Comment by JanuszL** [comment]
Hi,
>how can we run DALI in a separate process like the official practice with PyTorch DataLoader and Dataset

You don't need too. The reason why PyTorch uses multiple processes is the lack of true support in Python for multi-threaded processing because every line of code in python needs to obtain GIL. In the case of DALI we really on native code OS threads and we don't suffer from that problem.

> DALI cpu mode cost two much CPU and it runs in the same process with training process

You can adjust the number of threads that DALI uses during the pipeline construction. The amount of work done in the training thread is rather minimal (if you use asynchronous and pipelined executor what is the default setting) and the rest happens in the background threads. In the end, it doesn't matter much if you have multiple threads or processes as they use the CPU is more or less the same way.
Is there any particular symptom that makes you think that multiprocessing is better than multithreading?

**Comment by weberxie** [comment]
Thanks for your explanation!

I was investigating a problem, I ran the ResNet-50 With PyTorch DALI and Horovod, Horovod's timeline show that, the calculation time of different rank is different, and I watched that the training process cost too much CPU, even though the time of get next batch is almost 0 ms. So, I was doubt that whether the DALI's threads affect the training thread, then caused the different rank slows down randomly.

**Comment by JanuszL** [comment]
> I watched that the training process cost too much CPU

It depends on how the load is distributed among the threads and cores involved.

> even though the time of get next batch is almost 0 ms, So, I was doubt that whether the DALI's threads affect the training thread, then caused the different rank slows down randomly.

It depends on your pipeline configuration how much CPU resources DALI needs. Even if you are using GPU accelerated JPEG decoder CPU is heavily involved in the initial JPEG decoding part. Even if the time of getting the next batch is almost 0 ms in most cases when in one rank it is bigger than on the other one all the training processes would wait for the slowest node. I would recommend to capture GPU profiles using Nsight Systems profiles and see what is going on between different ranks.

**Comment by weberxie** [comment]
@JanuszL Thanks for your kind reply, I have already profile it with nvprof and didn't find obvious problem, I'll take a deeper look.
