### ISSUE TITLE
External support ops

### ISSUE THREAD

**Issue by crucifyml** [NVIDIA/DALI#215]
Use external inputs as support ops to manually set augmentation arguments.

**Comment by klecki** [comment]
Internally tracked as DALI-239.

**Comment by JanuszL** [comment]
Hi,
This sounds like a good idea. We hope to make it working some day, but external input even now is not fully supported in TF due to difference how DALI is integrated with TF and how it is it with PyTorch and MxNet.
Of course if you have some spare time and want to implement this feature all external contributions are more than welcome.
Br,
Janusz

**Comment by JanuszL** [comment]
@crucifyml - this is possible in the master branch and will be in the incoming 0.16 release. In the meantime you can try nightly build.
