### ISSUE TITLE
Alternative operation of PIL.Image.BICUBIC

### ISSUE THREAD

**Issue by bhheo** [NVIDIA/DALI#2150]
Hi

I'm implementing random interpolation for ImageNet with DALI.

Original code uses PIL resize function with bilinear and bicubic interpolation.
I initially tried with `INTERP_LINEAR` and `INTERP_CUBIC`, but the results were not good.
So, I want to implement it with a more similar operations.

As I know, `PIL.Image.BILINEAR` can be replaced with `INTERP_TRIANGULAR`.
However, in the case of `PIL.Image.BICUBIC`, I'm not sure which operation can replace it.
I would like to know which interpolation is most similar to `PIL.Image.BICUBIC`.

**Comment by mzient** [comment]
As a background, I'll quote PIL documentation:
> Bicubic and bilinear downscaling
> 
> From the beginning BILINEAR and BICUBIC filters were based on affine transformations and used a fixed number of pixels from the source image for every destination pixel (2x2 pixels for BILINEAR and 4x4 for BICUBIC). This gave an unsatisfactory result for downscaling. At the same time, a high quality convolutions-based algorithm with flexible kernel was used for ANTIALIAS filter.
>
> Starting from Pillow 2.7.0, a high quality convolutions-based algorithm is used for all of these three filters.

We use bicubic _interpolation_ and, as the name implies, it doesn't perform any kind of low-pass fitlering - every output pixel is a product of fitting a bicubic spline to a 4x4 pixel grid and downscaling by factors larger than approximately 2 will produce aliasing artifacts. This is expected and this is also what you'll get in OpenCV or Tensorflow.
If we change our behavior to mimic PIL, we'll no longer be performing bicubic interpolation, but rather bicubic filtering.
For now, you can switch to `INTERP_LANCZOS3` resampling (it should be similar enough) which performs antialiasing (we actually switched to doing so in recent release). You can even go halfway and use bicubic for upscaling and Lanczos for downscaling by specifying `mag_filter`/`min_filter` instead of `interp_type`.

**Comment by bhheo** [comment]
@JanuszL Thank you for your kind answer.
I have a few simple questions.

- Is `INTERP_LANCZOS3`  in `v0.23.0` including antialiasing ? or should I use more recent version?
- Are other operations `INTERP_TRIANGULAR` and `INTERP_GAUSSIAN` also using antialiasing in recent version?
- What is the kernel size for `INTERP_GAUSSIAN` and `INTERP_LANCZOS3` ?

**Comment by mzient** [comment]
1. The transition from Lanczos interpolation to Lanczos low-pass fitler is in 0.24. It should be available soon; you can use one of our nightlies.
2. Triangular and Gaussian were the two initial filters for downscaling and they intrinsically support antialiassing.
3. Lanczos3 has a constant support of 7 samples (from 0.24 it can is greater when downscaling). Gaussian has a support of `4*sqrt(2)*sigma`.
Sigma for Gaussian filter is:
`sqrt(2)/4` when upscaling
`sqrt(2)/4 * ratio` when dowsncaling

**Comment by bhheo** [comment]
@mzient Thanks

**Comment by guanfuchen** [comment]
@bhheo 
"As I know, PIL.Image.BILINEAR can be replaced with INTERP_TRIANGULAR." Can you give the reference for this replacement?

**Comment by bhheo** [comment]
@guanfuchen 
I can't find official documents. but following issues can be the references.
https://github.com/NVIDIA/DALI/issues/1094
https://github.com/NVIDIA/DALI/issues/1507

**Comment by JanuszL** [comment]
I think it is more about PIL documentation than DALI. DALI does exactly what you are asking for. PIL does things under the hood and doesn't advertise it - you can check https://github.com/python-pillow/Pillow/issues/2718 for example.
The exact place in the Pillow source code is [here](https://github.com/python-pillow/Pillow/blob/master/src/libImaging/Resample.c#L197) - the size of the filter depends on the scale when downscaling. So bilinear filter takes more than two input pixels to produce the output and changes to Triangular one.
