### ISSUE TITLE
[Question] No data was provided to the ExternalSource. Make sure to feed it properly

### ISSUE THREAD

**Issue by kindoblue** [NVIDIA/DALI#2196]
I defined a pipeline using an `ExternalSource`. It works when I do `pipeline.build()` and `pipeline.run()`. When I use it to define a `tf.data.Dataset` (DALIDataset) and feed to Keras model.fit(), I get:

 `No data was provided to the ExternalSource. Make sure to feed it properly`. 

Using Tensorflow 2.2.0 and Dali 0.24. 

I tried eager mode, non-eager mode; I tried to explicitly call `feed_input` but with no success. Any suggestions on what to check?

**Comment by JanuszL** [comment]
Hi,
Due to the way how DALI is integrated with the TensroFlow (native code run as a TensroFlow operator inside the graph) we cannot run any arbitrary python code during the execution of what is a must in case of the ExternalSource. It seems that our documentation lost a note about lack of TensorFlow and ExternalSource cooperation, I just readded it in https://github.com/NVIDIA/DALI/pull/2201.

**Comment by JanuszL** [comment]
DALI 0.26 is available and should include the needed functionality.
