### ISSUE TITLE
How to do inplace operation when creating custom operators ?

### ISSUE THREAD

**Issue by JosephChenHub** [NVIDIA/DALI#2385]
hi, I would like to create a plugin, in which the memory access can be done in place. e.g., in the `RunImpl`:
```
template <>
void DummyPlugin<::dali::GPUBackend>::RunImpl(::dali::DeviceWorkspace &ws) {
        const auto &input1 = ws.Input<::dali::GPUBackend>(0);
        auto &output1 = ws.Output<::dali::GPUBackend>(0);  // input1 & output1 refer to a block of memory with same address

        // do something
        
        
}
```
Could you please give me some suggestions to achieve this?

**Comment by JanuszL** [comment]
Hi,
It is possible, you can check [reshape operator](https://github.com/NVIDIA/DALI/blob/master/dali/operators/generic/reshape.cc). However, it is possible only if you are not modifying the underlying data because inputs are shared by operators. So if you modify it then the next operator would see the wrong data, like:
```
input --> your_op
         \->resize
```
Resize would get modified data instead of raw input.

**Comment by JosephChenHub** [comment]
> Hi,
> It is possible, you can check [reshape operator](https://github.com/NVIDIA/DALI/blob/master/dali/operators/generic/reshape.cc). However, it is possible only if you are not modifying the underlying data because inputs are shared by operators. So if you modify it then the next operator would see the wrong data, like:
> 
> ```
> input --> your_op
>       \->resize
> ```
> 
> Resize would get modified data instead of raw input.

Thanks for your reply! It works!
