### ISSUE TITLE
i have a task for Action Recognition. How should I use DALI?

### ISSUE THREAD

**Issue by seeyouagain111** [NVIDIA/DALI#2571]
My Dataset  consists of videos、Bbox、 action beginning time in the video 、labels,Can i use DALI to load this dataset？

**Comment by seeyouagain111** [comment]
data like this ：
_video name  |    start second time | bboxes | labels_
00bYMWy5S7A | 3 | 0.438876 | 0.49188 | 0.525271 | 0.698892 | 17
00bYMWy5S7A | 3 | 0.438876 | 0.49188 | 0.525271 | 0.698892 | 3
00bYMWy5S7A | 3 | 0.692557 | 0.409143 | 0.778872 | 0.683814 | 14

**Comment by jantonguirao** [comment]
You could use a combination of VideoReader and ExternalSource. With VideoReader you'd read the portion of the video you are interested in and with the external source operator, you will load the bounding box information.

You'll have to convert your data into a file following the format required by VideoReader's file_list argument. See the documentation here:
https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.VideoReader

The idea would be to preprocess your data file in python, creating a temporary file_list file for VideoReader, and storing the bounding box information so that it can be fed to the external source node.

**Comment by seeyouagain111** [comment]
thanks, i will try it!

**Comment by JanuszL** [comment]
@seeyouagain111 I don't think it is that simple. This way you need to figure out what sequence DALI would yield each iteration based on the provided files, seq length, step, and stride.
For now, there is no way to drive one reader by the output from the other one in DALI. What you can do is:
- create your reader using [Python operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/index.html)
- use file_list argument, and provide a unique id to each part of the video. Then enable `enable_frame_num` and `enable_timestamps` in the reader, output these values from the pipeline and do retrieve an appropriate annotation that corresponds to the given label and frame stamp outside DALI (I think you can just load all annotations into python memory, it doesn't look to be that big).

**Comment by JanuszL** [comment]
Hi @seeyouagain111,

You can use [the `external source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.external_source.html) and then pass the loaded videos to [the `video decoder`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.experimental.decoders.video.html).
