### ISSUE TITLE
 Looking for nvjpegCreateEx - not found

### ISSUE THREAD

**Issue by owenustc** [NVIDIA/DALI#272]
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "8.0")
-- Found NVJPEG: /opt/dali/tools/cuda-linux64-nvjpeg/include (found suitable version "9.0", minimum required is "9.0")
-- Looking for nvjpegCreateEx
-- Looking for nvjpegCreateEx - not found
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find JpegTurbo: Found unsuitable version "1.4.2", but required is
  at least "1.5" (found /usr/include)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindJpegTurbo.cmake:41 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:90 (find_package)
  CMakeLists.txt:43 (include)

**Comment by JanuszL** [comment]
Hi,
```
-- Looking for nvjpegCreateEx
```
This line checks if your NVJPEG version supports new, extended API. If not it will still work. You can always update to 0.2.0 version available https://developer.nvidia.com/nvjpeg-release-candidate-download. It is info, not an error.
There real issue is:
```
Could NOT find JpegTurbo: Found unsuitable version "1.4.2", but required is
at least "1.5" (found /usr/include)
```
So I recommend to update your JpegTurbo library (one installed by apt-get is older, 1.5 need to be installed from sources). Other solution is to disable it -DBUILD_JPEG_TURBO=OFF, but we not recommend it.
