### ISSUE TITLE
FileReader: how to get (image, image) pairs rather than (image, label) pairs?

### ISSUE THREAD

**Issue by opetrova** [NVIDIA/DALI#274]
Hi,
Both my inputs and targets are images, but I am having trouble getting a Pipeline to output the correct (image, image) pairs. I used a FileReader to read and randomly shuffle the input images with labels, and another one to read the target images with those same labels:

    class imagePipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, imageset_dir, size):
        super(imagePipe, self).__init__(batch_size, num_threads, device_id)
        self.input = ops.FileReader(file_root=join(imageset_dir,'input'), random_shuffle=True)
        self.target = ops.FileReader(file_root=join(imageset_dir,'target'), file_list = join(datapath,'target', 'labels.txt'), random_shuffle=False)
        self.decode = ops.nvJPEGDecoder(device="mixed", output_type=types.GRAY)

The number of target images/labels is less than 1000, so I figured I would have all of them in the buffer, and find the correct targets corresponding to the shuffled batch of inputs in define_graph:

    def define_graph(self):   
        input_images, input_labels = self.input()
        target_images, target_labels = self.target()
        input_images = self.decode(input_images)
        target_images = self.decode(target_images)
        
This is where I run into a problem though... I want to return [input_images, targets] where targets[k] = target_images [input_labels[k]], but neither target_images nor input_labels can be indexed or iterated through. Is there a better way to go about it? Any help would be greatly appreciated!

**Comment by JanuszL** [comment]
Hi,
Currently DALI is no supporting use case you provided in the direct way. Still you may try to use ExternalSource to read data from you data set - https://github.com/NVIDIA/DALI/blob/master/docs/examples/external_input.ipynb. In this way you are not limited by the FileReader.
However due to way how DALI is integrated with TensorFlow it ExternalSource will not work with there. If you are using PyTorch or MxNet it should work well for you.
Internally tracked DALI-346.

**Comment by opetrova** [comment]
Thanks, I am using PyTorch, so I'll give ExternalSource a try!

**Comment by opetrova** [comment]
Janusz, just checking: 
In the example you provided, it looks like the inputs are shuffled only once, when the ExternalInputIterator object is initialised? So for each training epoch, the inputs will be read in the same order, or am I misreading this?
Thanks again!

**Comment by JanuszL** [comment]
Hi,
ExternalInputIterator is just auxiliary class provided as an example. What you really need to follow using ExternalSource is:
- create ExternalSource operator during pipeline initialization
- implement iter_setup in your pipeline. This method is called once before each time DALI runs the pipeline (beware that internally DALI, due to double buffering may call it anytime) and there you need to call feed_input. The first argument is the operator reference you are providing data to, the second is the data itself. In the provided example we are using ExternalInputIterator, but in your case, it may be any custom code that reads any amount of data in any way you like and just feeds ExternalSource with it.

**Comment by JanuszL** [comment]
Hi,
ExternalInputIterator is just auxiliary class provided as an example. What you really need to follow using ExternalSource is:
- create ExternalSource operator during pipeline initialization
- implement iter_setup in your pipeline. This method is called once before each time DALI runs the pipeline (beware that internally DALI, due to double buffering may call it anytime) and there you need to call feed_input. The first argument is the operator reference you are providing data to, the second is the data itself. In the provided example we are using ExternalInputIterator, but in your case, it may be any custom code that reads any amount of data in any way you like and just feeds ExternalSource with it.

**Comment by opetrova** [comment]
Hi,
Sorry, one more thing about this - is it not possible to get the epoch_size when using ExternalSource? (What exactly is meant by "epoch_size", by the way?)

Here is a code fragment from my Pipeline subclass:

    class ImagePipeline(Pipeline):
    def __init__(self, imageset_dir, image_size=64, input_dim=1, batch_size=64, num_threads=2, device_id=0):
        super(ImagePipeline, self).__init__(batch_size,
                                      num_threads,
                                      device_id,
                                      seed=12)        
        self.input = ops.ExternalSource()
        self.target = ops.ExternalSource()

    def define_graph(self):                                                                
        self.input_images = self.input(name="inputs")
        self.target_images = self.target(name="targets")

The pipeline works the way it is supposed to. However, when I try to create an equivalent of a dataloader for my Pytorch program via DALIGenericIterator, I cannot get the epoch_size. This:

    pipe = ImagePipeline(datapath, 128, 1, 2)
    pipe.build()
    pipe.epoch_size()
returns {}, and this:

      pipe.epoch_size("inputs")
gives me

      RuntimeError: [/opt/dali/dali/python/backend_impl.cc:633] Assert on "sizes.find(op_name) != sizes.end()" failed: Operator inputs does not expose valid epoch size.

**Comment by JanuszL** [comment]
Hi,
epoch_size is a number of samples that reader with given name sees. In the case of FileReader, it is a number of files it has discovered during initialization. For the external source is it not possible to define such thing as it is up to the user to feed data to the ExternalSource.
DALIGenericIterator uses this "size" to know when to stop iterating over the data set. We recommend using epoch_size() whenever possible to avoid any mistake and make training script portable. As you handle data loading on your own you probably know or are able to learn a number of samples that you are going to provide to the ExternalSource.
Br,
Janusz

**Comment by gbyy422990** [comment]
how to use ExternalSource  on multi gpus? @JanuszL

**Comment by JanuszL** [comment]
> how to use ExternalSource on multi gpus? @JanuszL

The same way as in the single GPU. It is the user's responsibility to do the sharding and making sure that each ExternalSource instance (each GPU) gets data from the different shard.
