### ISSUE TITLE
How to further boost the speed of data reading?

### ISSUE THREAD

**Issue by cfzd** [NVIDIA/DALI#2767]
I have a machine with eight GPU cards, and I found the data reading from SSD is the performance bottleneck, even with DALI. Is there any way to further boost the reading speed? 

I have the following ideas and I don't know which one is best to choose:
1. Ramdisk to store data instead of SSD
2. manually implement an external source that caches the dataset in memory, thus eliminating the reading from SSD.
3. Use GDS or Cufile

For the first one, my concern is that even the data is stored in the ramdisk, there is inevitable data copy from ramdisk to dali memory space. 

For the second one, I don't know simply eliminating the reading of image bytes could boost the speed to what extent (I think the major part is JPEG decoding). Moreover, some previous attempts show that the external source implemented by us would harm the performance (1-2% performance drop on ImageNet compared with `ops.FileReader`, possibly due to batch policy).

For the third one, I only found the `ops.NumpyReader` supports the GDS and Cufile, but the NumPy array is not a very good container for images, especially for a large dataset like ImageNet. Besides, I don't know the speed of GDS or Cufile, would it be faster?

Do you have any ideas or other solutions to this problem? Thanks!

**Comment by JanuszL** [comment]
Hi,

I don't think you can do much.
1), 2) your OS implements disc cache. So when you read data for the first time it stores it in the free portion of RAM. When you read it again, and RAM was not wiped out your data should be read directly from the disc cache. RAM disc would make this process more user-controlled by it would result in the same effect. You can check [vmtouch project](https://github.com/hoytech/vmtouch) and use it to prepopulate disc cache before you run DALI. You can even try something `numactl --interleave=0-7 vmtouch -t "${datadir}"` to take into account the 8 GPUs you have.
3) It is mostly to reduce the latency and CPU utilization. We won't go beyond your disc reads speed.

To make sure what is the major bottleneck I would recommend capturing a GPU profile and see if there data reading operation in DALI is the blocker and how your GPU utilization looks like (if there are gaps due to waiting for the data to be ready to the training)/

**Comment by cfzd** [comment]
Thanks!
