### ISSUE TITLE
the behavior of pad policy when using multi gpu

### ISSUE THREAD

**Issue by twmht** [NVIDIA/DALI#2881]
hi,

my dataset has 10 samples, the label of each sample is 0,1,2,3,4,5,6,7,8,9.

when using 4 gpus and batch size is 3 , dali will divide the dataset to 4 shards.

in each shard, the batch has some overlaps.

first shard: [0,1,2]
second shard: [2,3,4]
third shard: [5,6,7]
forth shard [7,8,9]

however, in the default behavior of pytorch (https://github.com/pytorch/pytorch/blob/master/torch/utils/data/distributed.py#L108) , it should be
first shard: [0,1,2]
second shard: [3,4,5]
third shard: [6,7,8]
forth shard [9,0,1]

I am not sure how to configure dali to have such policy.

any idea?

**Comment by JanuszL** [comment]
Hi @twmht,

In the DALI case it is:
```
first shard: [0,1]
second shard: [2,3,4]
third shard: [5,6]
forth shard [7,8,9]
```
By default DALI would move to the next shard when the current one is exhausted, so that is why you see:
```
first shard: [0,1,2]
second shard: [3,4,5]
third shard: [6,7,8]
forth shard [9,0,1]
```
The best would be to set `pad_last_batch=True` in the reader and `last_batch_policyPARTIAL` or `last_batch_policy=DROP` in the PyTorch DALI iterator. In that case, you are sure that you are not duplicating any sample during the epoch.
If you want to mimic what PyTorch does you can use the `files` argument of the reader and just pass 12 samples to it:
```
files=[0,1,2,3,4,5,6,7,8,9, 0, 1]
first shard: [0,1,2]
second shard: [3,4,5]
third shard: [6,7,8]
forth shard [9,0,1]
```

**Comment by twmht** [comment]
> In the DALI case it is:
  first shard: [0,1]
  second shard: [2,3,4]
  third shard: [5,6]
  forth shard [7,8,9]

for real?

I use dali 1.0.0

the first batch of each shard is 

```
first shard: [0,1,2]
second shard: [2,3,4]
third shard: [5,6,7]
forth shard [7,8,9]
```

any mistake?

**Comment by JanuszL** [comment]
>for real?
>
> I use dali 1.0.0

That is how shards are defined in DALI, but as I said when one is exhausted it moves to the next one, that why you see samples from the next shard. If you apply `pad_last_batch=True` you can get:
```
first shard: [0,1,1]
second shard: [2,3,4]
third shard: [5,6,6]
forth shard [7,8,9]
```

**Comment by twmht** [comment]
thank you.
