### ISSUE TITLE
Must the pipeline be serialized when using it in tensorflow?

### ISSUE THREAD

**Issue by leoyang233** [NVIDIA/DALI#289]
Why can't I just use the pipeline class?

**Comment by JanuszL** [comment]
Hi,
It is due to TensorFlow design where only operators can create tensors and there is no easy (obvious) way to copy data from Dali to tensor itself as we do for PyTorch or MxNet.
So currently flow is following:
- create DALI pipeline in the Python
- serialize DALI pipeline
- create TensorFlow operator in native code by deserializing  DALI pipeline
- DALI TensorFlow native operator is executed, creates TensorFlow tensors and copy data from DALI pipeline to them
@ptrendx, @Kh4L I just started to think if we can do something like https://www.tensorflow.org/api_docs/python/tf/py_func and https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/lib/core/py_func.cc ?
@leoyang233 even if idea above is possible to do we need to check how much time round trip native code->Python->native code takes and how that may affect the performance.

**Comment by Kh4L** [comment]
I saw tf.py_func in the early stage of development of our Tensorflow Op. This approach would drastically affect the performances.
@leoyang233 as @JanuszL stated, our current method « define pipeline in Python  -> serialize -> execute the pipeline in C++ inside a custom TF op » provides the best compromise between ease of use and performance.
However what we could do, is having wrapper for the TF op that would take the user defined pipeline Python Obect and calls `serialize` + pass the result to the actual op, transparently to  the user.

**Comment by JanuszL** [comment]
Done in https://github.com/NVIDIA/DALI/pull/310.
