### ISSUE TITLE
DALI install redirect to https://developer.download.nvidia.cn and receive 404 not found

### ISSUE THREAD

**Issue by yangdian96** [NVIDIA/DALI#2991]
When I try install nvidia-dali via pip command:
`pip3 install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda100`
The url return a 301 redirect and jump to https://developer.download.nvidia.cn and returns me a 404 not found error

The https://developer.download.nvidia.cn is NOT WORKING!

![image](https://user-images.githubusercontent.com/84713386/119631097-269eea80-be42-11eb-894f-39fa36560dfb.png)

**Comment by JanuszL** [comment]
Hi,
Please update the pip to the latest version:
```
pip3 install -- upgrade pip
```
because it tries to select manylinux1 based build instead of the latest release. Also, it tries to download `future` from the Nvidia page instead of PyPI.
You can also try the direct links from [this page](https://github.com/NVIDIA/DALI/releases/tag/v1.2.0).

**Comment by JanuszL** [comment]
Closing as stalled.
