### ISSUE TITLE
Warning: Decoding on a default stream. Performance may be affected.

### ISSUE THREAD

**Issue by psandev** [NVIDIA/DALI#3048]
Hi,
I am getting the following warning:
[/opt/dali/dali/operators/reader/nvdecoder/nvdecoder.cc:87] Warning: Decoding on a default stream. Performance may be affected.

What does it mean and how seriously should I take it? What to do to fix it?

**Comment by JanuszL** [comment]
Hi @psandev,

There is an issue with the most recent GPU driver (>= 460.x) that causes invalid memory access when the decoder work on non-default stream. It may affect performance a bit, it depends on your workload how much you can be affected.
It should be fixed in one of the next driver releases. You can also downgrade the driver (not recommended).
