### ISSUE TITLE
using DALI backend with triton when batch>1

### ISSUE THREAD

**Issue by FreshZZ** [NVIDIA/DALI#3234]
I try to use DALI backend with triton

`data = np.fromfile(img_path, dtype='uint8')`
the data from different images has different length
so how can I put them in one batch

```python
@dali.pipeline_def(batch_size=32, num_threads=4, device_id=0, prefetch_queue_depth=1, exec_pipelined=False, exec_async=False) #, prefetch_queue_depth=1, exec_pipelined=False, exec_async=False
def pipe():
    images = dali.fn.external_source(device="cpu", name="DALI_INPUT_0", layout="HWC")
    images_org = dali.fn.decoders.image(images, device="mixed", output_type=types.RGB)
    images = ops.Resize(
            device="gpu",
            image_type=types.RGB,
            interp_type=types.INTERP_LINEAR,
            resize_x=640,
            resize_y=360)(images_org)
```

**Comment by szalpal** [comment]
Hi, @FreshZZ !

I took the liberty to format your question a little bit, so that the code is more readable.

If I understood your problem correctly, you are trying to load compressed images into a batch. However, as always with compressed images, every such image has different length of the buffer, so the Triton client possibly protests against such thing.

The solution is to pad all the buffers in the batch with zeros, so that they have the same length, e.g.
```
img1.shape = [367]
img2.shape = [523]
img3.shape = [354]

After padding: img1.shape = img2.shape = img3.shape = [523]
```
In numpy you can typically do something like:
```python
def array_from_list(arrays):
    """
    Convert list of ndarrays to single ndarray with ndims+=1
    """
    lengths = list(map(lambda x, arr=arrays: arr[x].shape[0], [x for x in range(len(arrays))]))
    max_len = max(lengths)
    arrays = list(map(lambda arr, ml=max_len: np.pad(arr, ((0, ml - arr.shape[0]))), arrays))
    for arr in arrays:
        assert arr.shape == arrays[0].shape, "Arrays must have the same shape"
    return np.stack(arrays)

images = []
img_paths = [...]
for img_path in img_paths:
    images.append(np.fromfile(img_path, dtype='uint8'))
input_batch = array_from_list(images)
```
---
Let me also note, that you may possibly want to use [dynamic batching](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#dynamic-batcher). Typically in this approach, you would like to send a batch of 1 sample to the server, and the server itself is going to combine the samples sent into a batch. DALI Backend supports dynamic batching - all you need to do is to add the following to your `config.pbtxt` file:
```
dynamic_batching {
  preferred_batch_size: [ 256 ]
  max_queue_delay_microseconds: 500
}
```

**Comment by banasraf** [comment]
@FreshZZ 
BTW, you can use `fn.resize` instead of `ops.Resize` and you can omit the `device` argument, so it would look like that:
```python
images = fn.resize(images_org,
                   image_type=types.RGB,
                   interp_type=types.INTERP_LINEAR,
                   resize_x=640,
                   resize_y=360)
```

**Comment by FreshZZ** [comment]
@szalpal @banasraf  Your answers are very helpful to me. Thank you very much
