### ISSUE TITLE
Confusing about conditional operators in define_graph

### ISSUE THREAD

**Issue by makaaay** [NVIDIA/DALI#3483]
Hi, I am using the different size Images in my training pipeline , but when I want to do something like "if h>w，do A things ,else : do B things", I found the dali not support "if conditional".
So, if i want do the conditional operators like ：
```
h,w,_ = image.shape
# define graph
if h>w:
fn.crop(image, crop=self.input_size, crop_pos_x=crop_x_ratio, crop_pos_y=crop_y_ratio, out_of_bounds_policy="pad")
else:
fn.resize(image, resize_x=resize_w, resize_y=resize_h, interp_type=DALIInterpType.INTERP_LINEAR)
```
how should i do in dali ?

Then i have another confusing thing , the "pading operators" in dali alway pad in right / bottom, how can i pad the image on left/top  side?  i try to solve this problem using "paste op",but i can not paste an image (like 8x6) in a square canvas (like 10x10).   Cause that paste can only paste image in a same ratio canvas.

Thanks.

**Comment by mzient** [comment]
@makaaay
1. Unfortunately, there's no way to conditionally apply an operator (especially one that changes the shape).
2. Padding - you can pad with `crop` with `out_of_bounds_policy="pad"` - then you can select `crop_pos` which is a relative position defined so that 0 aligns the contents to the left and the padding is on the right and 1 means that the image is aligned to the right and the padding is at the left.

**Comment by makaaay** [comment]
Got it, thank you! the second way has solved my problem.
