### ISSUE TITLE
Inconsistent test results after deploying to DALI

### ISSUE THREAD

**Issue by lincong8722** [NVIDIA/DALI#3610]
When I deploy image preprocessing to DALI, the test results are inconsistent with the original,I don't know what caused it
The original preprocessing code:
```
    def initialize(self, args):
        # You must parse model_config. JSON string is not parsed here
        self.model_config = model_config = json.loads(args['model_config'])

        # Get OUTPUT0 configuration
        output0_config = pb_utils.get_output_config_by_name(model_config, "prep_output0")

        # Convert Triton types to numpy types
        self.output0_dtype = pb_utils.triton_string_to_numpy(output0_config['data_type'])
        self._MEAN = [ 0.456, 0.485, 0.406]
        self._SD = [0.224, 0.229, 0.225]
        self.resize = 224

    def scale(self, size, im):
        """Performs scaling (HWC format)."""
        h, w = im.shape[:2]
        if (w <= h and w == size) or (h <= w and h == size):
            return im
        h_new, w_new = size, size
        if w < h:
            h_new = int(math.floor((float(h) / w) * size))
        else:
            w_new = int(math.floor((float(w) / h) * size))
        im = cv2.resize(im, (w_new, h_new), interpolation=cv2.INTER_LINEAR)
        return im.astype(np.float32)

    def center_crop(self, size, im):
        """Performs center cropping (HWC format)."""
        h, w = im.shape[:2]
        y = int(math.ceil((h - size) / 2))
        x = int(math.ceil((w - size) / 2))
        im_crop = im[y : (y + size), x : (x + size), :]
        assert im_crop.shape[:2] == (size, size)
        return im_crop

    def color_norm(self, im):
        """Performs per-channel normalization (CHW format)."""
        for i in range(im.shape[0]):
            im[i] = im[i] - self._MEAN[i]
            im[i] = im[i] / self._SD[i]
        return im

    def resize_image(self, input_image):
        img = cv2.imdecode(input_image, 1)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = self.scale(256, img)
        img = self.center_crop(self.resize, img)
        img = np.transpose(img, (2,0,1))
        img = img / 255.0
        img = self.color_norm(img)        
        return img

```

**Comment by lincong8722** [comment]
Preprocessed code after deployment to DALI:

`@dali.pipeline_def(batch_size=256, num_threads=4, device_id=0)
def pipe():
    images = dali.fn.external_source(device="cpu", name="prep_input0")
    images = dali.fn.decoders.image(images, device="mixed", output_type=types.RGB)
    images = dali.fn.resize(images, size=[256, 256], mode="not_smaller")
    images = dali.fn.crop_mirror_normalize(images,
                                           dtype=types.FLOAT,
                                           crop_pos_x = 0.5,
                                           crop_pos_y = 0.5,
                                           crop_w = 224,
                                           crop_h = 224,
                                           output_layout="CHW",
                                           scale=1/255.0,
                                           mean=[0.456, 0.485, 0.406],
                                           std=[0.224, 0.229, 0.225])
    return images`

**Comment by lincong8722** [comment]
When I use mean=[0.456*255, 0.485*255, 0.406*255],std=[0.224*255, 0.229*255, 0.225*255],the test results are much difference than the original,so I revise to mean=[0.456, 0.485, 0.406],std=[0.224, 0.229, 0.225]，Although the difference between the test results is small, it is still different

**Comment by JanuszL** [comment]
Hi @lincong8722,

There could be several sources of discrepancies:
- OpenCV uses libjpeg-turbo while `dali.fn.decoders.image(device="mixed")` uses nvJpeg. Both yield a bit different results due to different subsampling strategies (libjepg-turbo uses something called `Fancy upsampling`). Both approaches are valid but a but different:
decoded by OpenCV:
![image](https://user-images.githubusercontent.com/39967756/148921316-14bfb952-d72d-4441-9413-89731672ffc7.png)
decoded by DALI (mixed)
![image](https://user-images.githubusercontent.com/39967756/148921350-5a231662-1ba1-4745-8c80-1c7c910baf57.png)
decoded by DALI (cpu)
![image](https://user-images.githubusercontent.com/39967756/148923857-41bb299a-1779-40af-a048-1776e6879933.png)
difference * 10 OpenCV vs DALI (mixed)
![image](https://user-images.githubusercontent.com/39967756/148921840-09613ec7-aa29-4871-9355-b3e38d461601.png)
difference * 10 OpenCV vs DALI (cpu)
![image](https://user-images.githubusercontent.com/39967756/148923946-9e5a231d-27c9-4057-8f9a-82de4646f880.png)
- you should set `subpixel_scale=False` and interpolation type to linear (the default is traingular) `dali.fn.resize`  `fn.resize(images, interp_type=types.DALIInterpType.INTERP_LINEAR, subpixel_scale=False, size=[256, 256], mode="not_smaller")`
resized by OpenCV
![image](https://user-images.githubusercontent.com/39967756/148924762-4eb9c077-591c-414d-a7ca-fbcd4b92fb47.png)
resized by DALI
![image](https://user-images.githubusercontent.com/39967756/148924710-25c07f57-a565-433e-98eb-bc76db465d36.png)
difference * 10 OpenCV vs DALI (cpu)
![image](https://user-images.githubusercontent.com/39967756/148925047-e148ace7-f3ee-439f-887f-e706dcaf80d3.png)
- there is no scale parameter in `crop_mirror_normalize`, what you need to do is:
  ```
  fn.crop_mirror_normalize(resized,
                           dtype=types.FLOAT,
                           crop_pos_x = 0.5,
                           crop_pos_y = 0.5,
                           crop_w = 224,
                           crop_h = 224,
                           output_layout="HWC",
                           mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                           std=[0.229 * 255,0.224 * 255,0.225 * 255])
  ```
  cropped by OpenCV
  ![image](https://user-images.githubusercontent.com/39967756/148928083-4767408f-24ce-4447-b792-eaf3421e90d0.png)
  cropped by DALI
  ![image](https://user-images.githubusercontent.com/39967756/148928039-bab3af77-9d2a-4732-a118-7042840f5a5e.png)
  difference * 10 OpenCV vs DALI (cpu)
  ![image](https://user-images.githubusercontent.com/39967756/148928119-35d855ef-c795-4016-ba98-c9944ff8c08a.png)

So the final code should be like:
```
@dali.pipeline_def(batch_size=256, num_threads=4, device_id=0)
def pipe():
    images = dali.fn.external_source(device="cpu", name="prep_input0")
    images = dali.fn.decoders.image(images, device="mixed", output_type=types.RGB)
    resized = fn.resize(images, interp_type=types.DALIInterpType.INTERP_LINEAR, subpixel_scale=False, size=[256, 256], mode="not_smaller")
    cropped = fn.crop_mirror_normalize(resized,
                                       dtype=types.FLOAT,
                                       crop_pos_x = 0.5,
                                       crop_pos_y = 0.5,
                                       crop_w = 224,
                                       crop_h = 224,
                                       output_layout="HWC",
                                       mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                                       std=[0.229 * 255,0.224 * 255,0.225 * 255])
    return images
```
(assuming that you are okay with DALI "mixed" decoder misalignment)

**Comment by lincong8722** [comment]
@JanuszL After the correction, the accuracy is the same, thank you so much!!
