### ISSUE TITLE
Stacked random generators

### ISSUE THREAD

**Issue by gemenerik** [NVIDIA/DALI#3699]
I am trying to implement asymmetric augmentations to an optical flow pipeline. This implies applying a slightly different augmentation to the second image of an image pair and correcting the optical flow ground truth for it.

Let's consider a generated 'translation' due to a shifted crop as it is one of the simplest examples. Check out figure 3.6 in ["Advanced data augmentation for the RAFT optical flow approach"](http://dx.doi.org/10.18419/opus-11842) for a pretty graphical representation of this asymmetrical augmentation.

---

For each image in a batch:
1. Generate a random scaling factor and apply a resize.
```python
scaling_factor = fn.random.uniform(range=[0.68, 1.75])  # input image at 0.68 scale or larger guarantees a successful crop size at our fixed crop size
scaled_width = (scaling_factor * input_width)
scaled_height = (scaling_factor * input_height)
image = fn.resize(image, resize_x=scaled_width, resize_y=scaled_height)
```
2. Generate a random crop center based on the scaling factor generated above and a predefined fixed crop size. Apply to image 1.
```python
max_crop_center_x = (
                    324  # target width
                    / 2
                    / scaling_factor  # only possible if replaced with a fixed number
                    / 512  # input width
                )
crop_center_x = fn.random.uniform(
                    range=[
                        max_crop_center_x,
                        1 - max_crop_center_x,
                    ]
                )

# same for y

image0 = fn.crop(
                    image0,
                    crop=(244, 324),
                    crop_pos_x=crop_center_x,
                    crop_pos_y=crop_center_y,
                )

```
3. Generate a second, shifted crop center. Apply to image 2.
4. Correct optical flow ground truth by adding/subtracting the pixel shift between crop centers across the relevant channel (horizontal or vertical flow channel).
```python
asymmetric_displacement_x = translated_crop_center_x - crop_center_x
asymmetricly_translated_flow_u = types.Constant(value=asymmetric_displacement_x, shape=[324, 244])
```
---

Such a pipeline already fails when generating a random crop center in step 2, because it feeds a `DataNode` into the random generator.

```
TypeError: float() argument must be a string or a number, not 'DataNode'
```

Step 4 is similar to #2832, only I want to dynamically assign a value to the generated `Constant` based on the shift between crops. The shape of the `Constant` is fixed to the crop size.

```
TypeError: Unexpected type: <class 'nvidia.dali.pipeline.DataNode'>
```

Default 'random' operators are not an option because I need information about the applied transformations to modify the ground truth values.

---
So I am wondering if there is a workaround for;
* Feeding randomly generated values into another random generator.
* Filling a constant shape with a randomly generated value

If possible such that each image in a batch is augmented differently.

**Comment by mzient** [comment]
Hello @gemenerik , thanks for using DALI and reaching out to us!

I'll answer your questions first and then move one to propose a better (at least in my opinion) approach to your problem.

> Feeding randomly generated values into another random generator.
that's not possible - at least not if by "feeding into" you mean altering the distribution parameters

> Filling a constant shape with a randomly generated value
Yes, you can do that. One way to achieve that is to use a constant zero-filled buffer and add your randomly generated value to it. While DALI doesn't have directional broadcasting yet, it does support broadcasting of scalars. In order to broadcast two values (dx, dy) you'd need to have two intermediate uniformly filled arrays and stack them:
```Python
import nvidia.dali as dali
import nvidia.dali.fn as fn
import numpy as np

@dali.pipeline_def(batch_size=1, device_id=0, num_threads=3)
def my_pipe():
    dx = fn.random.uniform(device="gpu", range=[-1, 1])
    dy = fn.random.uniform(device="gpu", range=[-1, 1])
    flow_dx = dx + np.zeros(shape=[480,640], dtype=np.float32)
    flow_dy = dy + np.zeros(shape=[480,640], dtype=np.float32)
    flow_field_delta = fn.stack(flow_dx, flow_dy, axis=2)
    return flow_field_delta

pipe = my_pipe()

pipe.build()
o, = pipe.run()
print(o)
```

This will not allow you to implement things like asymmetric rotation/scaling/flipping from the paper.
Assuming that you're fine with plain bilinear interpolation (without antialiasing), then you can use warp_affine to implement the augmentations. You can then use your transform matrix to adjust your flow vectors. To be able to do that you have to go from flow vectors, which are relative, to absolute pixel positions (and then back).

The toy example below uses a 2-frame sequence, calculates an optical flow, then applies an extra affine transform to the second frame in the sequence and adjusts the optical flow accordingly.
```Python
@pipeline_def
def optical_flow_pipe():
    video = fn.readers.video(device="gpu", filenames=video_filename, sequence_length=2)
    
    f0 = video[0]
    f1 = video[1]
    
    w = 1280  # known size of the input video
    h = 720
    grid = 4  # spacing of flow vectors

    fw = 1280 // grid  # size of the motion vector field
    fh = 720 // grid

    x = np.arange(fw).reshape([1, fw]) + 0.5  # (0.5, 0.5) is a pixel center
    y = np.arange(fh).reshape([fh, 1]) + 0.5
    xy = np.stack([x, np.zeros_like(x)], axis=2) + np.stack([np.zeros_like(y), y], axis=2)
    xy = xy[np.newaxis] * grid  # now go from optical flow grid to source image coordinates

    m = fn.transforms.rotation(angle=15, center=[w/2, h/2])
[optical_flow_example.zip](https://github.com/NVIDIA/DALI/files/8124892/optical_flow_example.zip)

    f2 = fn.warp_affine(f1, matrix=m, inverse_map=True)
    
    video2 = fn.stack(f0, f2, axis=0, axis_name='F')
    
    of = fn.optical_flow(video, output_grid=grid)
    of2 = fn.optical_flow(video2, output_grid=grid)

    # optical flow augmentation goes here
    of3 = fn.coord_transform(of + xy, MT=m) - xy
    
    
    return video, video2, of, of2, of3
```

I've attached a modified optical_flow example that uses the code above. It shows you the following:
frame0
frame1
transformed frame1
flow(frame0 -> frame1)
flow(frame0 -> transformed frame1)
transformed flow(frame0 -> frame1)

**Comment by mzient** [comment]
I'm happy that I could be of help.

Regarding inverse map - yeah, it depends on your definition of optical flow. If your flow vector is defined as "an offset to the place where given pixel was in previous frame"  then yes, inverse_map should be false. If it's defined as "the offset by which a point/object has moved from frame A to B", then it should be `True`.
