### ISSUE TITLE
Crop after stack fails

### ISSUE THREAD

**Issue by castim** [NVIDIA/DALI#3716]
Hello,

When I run the following code:

```python
from tqdm import tqdm
from nvidia import dali
import nvidia.dali.fn as fn

sintel = ["../../sintel_trailer-1080p-g5.mp4"]
@dali.pipeline_def
def video_pipeline():
    seq = fn.readers.video(device="gpu", filenames=sintel, sequence_length=2, random_shuffle=True, step=5)
    images = []

    for i in range(2):
        im = fn.element_extract(seq, element_map=i)
        images.append(im)
    seq = fn.stack(*images)
    seq = fn.crop(seq, crop_w=256, crop_h=256)
    return seq

pipe = video_pipeline(batch_size=16, num_threads=1, device_id=0)
pipe.build()

for i in tqdm(range(99999999)):
    batch = pipe.run()[0]
```

I get this error:
```
[/opt/dali/dali/operators/image/crop/crop.h:43] Assert on "in_layout.ndim() == input.shape().sample_dim()" failed
```

I am doing this operation to apply image operations on a sequence. It seems that using crop after stack in this case fails. However, if I don't crop, the images look fine.
Am I doing something wrong?

The input video is encoded in the following way (using [sintel trailer 1080p](https://download.blender.org/durian/trailer/sintel_trailer-1080p.mp4) )
```
ffmpeg -i sintel_trailer-1080p.mp4 -an -g 5 sintel_trailer-1080p-g5.mp4
```

**Comment by jantonguirao** [comment]
Hi @castim.

Crop operator complains that the number of dimensions in the input doesn't match the layout metadata. This is because `stack` operator didn't receive the new `axis_name` and therefore didn't update the layout information. Some operators (such crop) rely on the layout info and will error out if there are inconsistencies.

To fix your code, please try:
```
seq = fn.stack(*images, axis_name='F')
```
Now, `crop` will see a `'FHWC'` layout for the input sequence.

**Comment by castim** [comment]
Thanks, it works!
