### ISSUE TITLE
shuffle data

### ISSUE THREAD

**Issue by sjbling** [NVIDIA/DALI#3735]
hi, now I using parallel external source, I want to shuffle the data , how to do it ,can you show me a example?

**Comment by stiepan** [comment]
Hi @sjbling,

There's no explicit utility that would permute the dataset, but you may use `epoch_idx` that is a member of `SampleInfo`/`BatchInfo` instance passed to the external source callback to permute the dataset on your own.

Assuming the external source runs in a sample mode (i.e. `batch=False`), each time the callback is called, it receives `idx_in_epoch` as a part o `sample_info` instance and is expected to return a sample that is uniquely identified by the `idx_in_epoch`. Now, you may use some function `keyed_permutation : epoch_idx -> idx_in_epoch -> idx_in_epoch` that for a given `epoch_idx` is a permutation of the indices in the dataset. The idea is for the callback to return `keyed_permutation(epoch_idx, idx_in_epoch)`-th sample instead of `idx_in_epoch`-th sample.

It could be implemented like that:

```
from nvidia.dali import pipeline_def
from nvidia.dali.types import SampleInfo
import nvidia.dali.fn as fn
import numpy as np

dataset_size = 100

class Callback():
    
    def __init__(self):
        self.dataset = [np.full((2, 2), i) for i in range(dataset_size)]  # dummy dataset
        self.perm = None  # permutation of indices
        self.last_seen_epoch = None  # so that we don't have to recompute the `self.perm` for every sample
    
    def __call__(self, sample_info : SampleInfo):
        if sample_info.idx_in_epoch >= len(self.dataset):
            raise StopIteration
        if self.last_seen_epoch != sample_info.epoch_idx:
            self.last_seen_epoch = sample_info.epoch_idx
            self.perm = np.random.default_rng(seed=42 + sample_info.epoch_idx).permutation(len(self.dataset))
        return self.dataset[self.perm[sample_info.idx_in_epoch]]

    
@pipeline_def
def pipeline():
    batch = fn.external_source(Callback(), batch=False, parallel=True)
    return batch
```

or not using callable class

```
from nvidia.dali import pickling

def create_sample_callback(seed=42):
    dataset = [np.full((2, 2), i) for i in range(dataset_size)]
    perm = None
    last_seen_epoch = None
    
    def sample_callback(sample_info : SampleInfo):
        nonlocal perm, last_seen_epoch
        if sample_info.idx_in_epoch >= len(dataset):
            raise StopIteration
        if last_seen_epoch != sample_info.epoch_idx:
            last_seen_epoch = sample_info.epoch_idx
            perm = np.random.default_rng(seed=42 + sample_info.epoch_idx).permutation(len(dataset))
        return dataset[perm[sample_info.idx_in_epoch]]                
    return sample_callback
    

@pipeline_def
def pipeline():
    batch = fn.external_source(create_sample_callback(), batch=False, parallel=True)
    return batch
```

**Comment by stiepan** [comment]
Hi @sjbling,

Following your question we decided to update examples on using parallel external source in DALI documentation. It now contains new section: Shuffling and sharding.

You can preview the updated notebook here: https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/data_loading/parallel_external_source.html

It will be included in the [stable documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/) with the incoming release.

**Comment by sjbling** [comment]
thanks all
