### ISSUE TITLE
get class map table and return file names in the batch

### ISSUE THREAD

**Issue by neurochen** [NVIDIA/DALI#3802]
I am wondering if there is a way to get the table to map folders to class indexes. And also, we would like to know if it's possible to return the file names or indexes in the current minibatch. This would be required when plotting sample images and networks' class predictions. It would also be nice to have some image-based analysis during training and validation evaluations. Thanks.

**Comment by szalpal** [comment]
Hi @neurochen !

> I am wondering if there is a way to get the table to map folders to class indexes.

Please refer to the [`fn.readers.file` documentation](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/operations/nvidia.dali.fn.readers.file.html#nvidia.dali.fn.readers.file). It explains, how you should put together the directory structure of the dataset. Since they are organised in directories named by index, you can easily create the table yourself - just traverse the dataset and discover, which file is contained in which directory.

> we would like to know if it's possible to return the file names or indexes in the current minibatch.

Sure, please use [`fn.get_property`](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/operations/nvidia.dali.fn.get_property.html#nvidia.dali.fn.get_property).

**Comment by neurochen** [comment]
Thanks for the quick response! Regarding the map table, what is the rule to sort folders? For indexes like 0 to 100, that's easy. But it's unclear for alphabet letter folders.

**Comment by neurochen** [comment]
Could you please provide a demo for fn.get_property? I tried different options without luck. There is no example online as well. Thanks.

**Comment by neurochen** [comment]
thanks. This is what I'm looking for. How about the sorting rules for classes?

**Comment by JanuszL** [comment]
Hi @neurochen,

Could you be more specific regarding:
> the sorting rules for classes?

Do you want to know how DALI sorts samples?

**Comment by szalpal** [comment]
@neurochen ,

Unfortunately, for `FileReader`, DALI does not support custom labels - these has to be integers. So this directory layout is improper:
```
<file_root>/A/image0.jpg
<file_root>/A/world_map.jpg
<file_root>/A/antarctic.png
<file_root>/Animals/cat.jpeg
<file_root>/1/dog.tif
<file_root>/2/car.jpeg
<file_root>/2/truck.jp2
```
You would need to have integers as labels:
```
<file_root>/0/image0.jpg
<file_root>/0/world_map.jpg
<file_root>/0/antarctic.png
<file_root>/1/cat.jpeg
<file_root>/1/dog.tif
<file_root>/2/car.jpeg
<file_root>/2/truck.jp2
```
