### ISSUE TITLE
fn.get_property

### ISSUE THREAD

**Issue by jasonxzhou** [NVIDIA/DALI#3838]
Hi DALI Team,
I am attempting to use the `fn.get_property` operator. According to the docs, `gpu` is a supported backend, but I'm running into the following issue (I've also attached a rough code snippet): 
Snippet:
```
rgb_files, _ = fn.readers.file(file_root=root, files=files, shard_id=shard_id, num_shards=num_shards)
info = fn.get_property(rgb_files, key="source_info", device='gpu')
```

Error with `gpu` backend: 
```
RuntimeError: Critical error in pipeline:
Error when executing GPU operator GetProperty, instance name: "__GetProperty_5", encountered:
[/opt/dali/dali/pipeline/workspace/workspace.h:544] Assert on "tensor_meta.storage_device == StorageDevice::GPU" failed: Input with given index (0) does not have the calling backend type (GPUBackend)
```

Switching to `cpu` backend instead produces: 
```
RuntimeError: [/opt/dali/dali/pipeline/data/tensor_list.h:568] Assert on "this->IsDenseTensor()" failed: All tensors in the input TensorList must have the same shape and be densely packed.
```
Thanks very much.

**Comment by JanuszL** [comment]
Hi @jasonxzhou,

You cannot do:
```
rgb_files, _ = fn.readers.file(file_root=root, files=files, shard_id=shard_id, num_shards=num_shards)
info = fn.get_property(rgb_files, key="source_info", device='gpu')
```
What you can do is:
```
rgb_files, _ = fn.readers.file(file_root=root, files=files, shard_id=shard_id, num_shards=num_shards)
info = fn.get_property(rgb_files, key="source_info)
info = info.gpu()
```
Or:
```
rgb_files, _ = fn.readers.file(file_root=root, files=files, shard_id=shard_id, num_shards=num_shards)
info = fn.get_property(rgb_files.gpu(), key="source_info, device='gpu')
```
The placement of the input to the operator needs to match the placement of the operator itself.

The error:
> RuntimeError: [/opt/dali/dali/pipeline/data/tensor_list.h:568] Assert on "this->IsDenseTensor()" failed: All tensors in the input TensorList must have the same shape and be densely packed.

Is caused by the fact that each tensor in the batch that is returned by framework DALI iterators needs to have the same dimensions so the batch can be represented as one tensor, with batch size being one of its dimensions. The `source_info` houses the file name, and its size is not uniform. What you can do is use [the `pad`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.pad) operator that would add trailing `0` that could be discarded later.

**Comment by jasonxzhou** [comment]
Thank you very much @JanuszL.
