### ISSUE TITLE
fn.erase operator does not support random filled value?

### ISSUE THREAD

**Issue by duduheihei** [NVIDIA/DALI#3881]
I used fn.erase for data augmentation,however it seems that the filled value has to be a fixed value rather  a random value. Will fn.erase  support random filled value? Here is my code:
```python
            anchor = fn.random.uniform(shape=2,range=(0.,0.8))  
            shape = fn.random.uniform(shape=2,range=(0.1,0.2))   
            fill_value = fn.random.uniform(range=(0,255))  
            images = fn.erase(images,anchor=anchor,shape=shape,fill_value=fill_value,normalized=True)  
````

**Comment by jantonguirao** [comment]
Hi @duduheihei. That's right, at the moment `fill_value` only support constant values (no data nodes).
This can be achieved with some small rework of the implementation, we just didn't have a use-case for it so far.
Can you describe what's your use-case, what model are you using, etc, so that we can get some background on how important would be to add this feature?
Thanks

**Comment by twmht** [comment]
@jantonguirao 

i also need the feature. I am not sure if it can improve the classification performance but i just want to try.

**Comment by jantonguirao** [comment]
@twmht @duduheihei This PR enables data notes for fill_value argument: https://github.com/NVIDIA/DALI/pull/4182
Once it's merged you can test it in the following nightly build.

**Comment by stiepan** [comment]
Hi @duduheihei

The DALI 1.18 has been released and the `fn.erase` operator now should support per-sample `fill_value`.
