### ISSUE TITLE
Question about multi-gpu training?

### ISSUE THREAD

**Issue by sunyuanrui** [NVIDIA/DALI#4388]
I'm honoured to use DALI, but I encounter a problem, could you guide me? 
I want to use 8 gpus to read images and training an object detection at the same time. Here is my code. When I create 8 gpus dali pipelines to read images, I get a batch list with 8 different gpus device, such as batch[0]->"cuda:0", batch[1]->"cuda:1",
but how to train each batch to the same device_id network?
```
num_gpus = 8
batch_size = 128
model = Model()
model = model.cuda()
model = torch.nn.DataParallel(model, device_ids=[x for x in range(num_gpus)])

@pipeline_def
def get_dali_pipeline():
      ...
     return images, bboxes


train_pipe = []
for id, device_id in enumerate(range(num_gpus)):
                train_pipe.append(get_dali_pipeline(batch_size=batch_size//num_gpus,
                                                                          shard_id=id, num_shards=num_gpus, 
                                                                          num_threads=4, device_id=device_id))


data_loader = DALIGenericIterator(
                                train_pipe,
                                ['images', 'bboxes'],
                                reader_name='Reader',
                            )


for index, batch in enumerate(data_loader):
     for i in range(num_gpus):
          image = batch[i]['images']
          bboxes = batch[i]['bboxes']
          outputs = model(image)
          loss += calc_loss(outputs, bboxes)
```
batch[0]['images'] at "cuda:0" and batch[1]['images']  at "cuda:1", how can I only sent batch[0]['images']  to network at "cuda:0" rather than separate to cuda 0-7 to train a network?

**Comment by jantonguirao** [comment]
@sunyuanrui It is recommended to use DistributedDataParallel instead of DataParallel (see https://pytorch.org/docs/stable/notes/cuda.html#cuda-nn-ddp-instead)

You will launch your script with `python -m torch.distributed.launch` and you only instantiate a single pipeline in your script, using `args.local_rank` as the `device_id`. You will also shard your dataset with `shard_id=args.local_rank` and `num_shards=args.world_size`. There will be a separate process per GPU, and each process will use a different GPU (for DALI and for training) and will see a different portion of the dataset.

You can see an example of using DALI and DistributedDataParallel here:
https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/resnet50/pytorch-resnet50.html
Code here: https://github.com/NVIDIA/DALI/blob/main/docs/examples/use_cases/pytorch/resnet50/main.py
More DALI documentation on this topic here: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/multigpu.html

Hope that helps

**Comment by sunyuanrui** [comment]
> @sunyuanrui It is recommended to use DistributedDataParallel instead of DataParallel (see https://pytorch.org/docs/stable/notes/cuda.html#cuda-nn-ddp-instead)
> 
> You will launch your script with `python -m torch.distributed.launch` and you only instantiate a single pipeline in your script, using `args.local_rank` as the `device_id`. You will also shard your dataset with `shard_id=args.local_rank` and `num_shards=args.world_size`. There will be a separate process per GPU, and each process will use a different GPU (for DALI and for training) and will see a different portion of the dataset.
> 
> You can see an example of using DALI and DistributedDataParallel here: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/resnet50/pytorch-resnet50.html Code here: https://github.com/NVIDIA/DALI/blob/main/docs/examples/use_cases/pytorch/resnet50/main.py More DALI documentation on this topic here: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/multigpu.html
> 
> Hope that helps

Thanks very much, it works well.
