### ISSUE TITLE
Supporting prefetch between pipeline stages

### ISSUE THREAD

**Issue by fversaci** [NVIDIA/DALI#4528]
Hi all,

recently we've been exploring a change in our [Cassandra-DALI plugin](https://github.com/crs4/cassandra-dali-plugin/) to allow the list of UUIDs (i.e., the "names" of the images) to be provided as an input to the reader, instead of as a function argument. This would allow more flexibility in the pipeline, which we could exploit in a particular application we are now targeting.

As a comparison, this would be similar to have the standard `FileReader` accept the list of files as an input from the previous module, instead of using the `file_root` argument.

The problem with this change is that it destroys our ability to concurrently prefetch images before passing them to the rest of the pipeline, since the pipeline-level prefetching, as I understand it, always runs the whole pipeline and, while it can help mitigating the variance in the loading time, it doesn't allow more loads to run in parallel.

It would be useful if there were a way to allow prefetching also at a stage level, where each module can directly request inputs from the previous one. In this way a module could, at setup time, fill its own prefetch queue before starting to produce outputs, as it is done now internally by the standard `FileReader` or, in our case, by our Cassandra reader.

I understand that this might require some major changes in the pipeline design, so I'd like to know if you're considering to support, sometime in the future, this kind of finer grain, per-stage prefetch or if you've already discussed it and ruled out its implementation.

Thanks!

**Comment by szalpal** [comment]
Hello @fversaci ,

this is a very interesting idea. Unfortunately, having prefetching between stages is not something we'd envision in the near future, as it redesigns whole execution model.

However, I believe there might be something, which could help you, but that depends on how your DALI pipeline looks like. We have freshly developed a new operator type called `InputOperator`.  https://github.com/NVIDIA/DALI/blob/ec2756a37bb5628a7a7a8ff8751735b1a9659546/dali/pipeline/operator/builtin/input_operator.h#L110

## TLDR
If by any chance your pipeline can be modified, that your `CassandraReader` can be provided with data using `feed_input`, the `InputOperator` supports prefetching:
```python
@pipeline_def
def pipe():
    inp = cassandra_reader(name="C_READ")
    ...

p = pipe(..., pretech_queue_depth=...)
p.build()
p.feed_input("C_READ", mydata)
p.run()  # will also prefetch
```
`CassandraReader` would need to be an `InputOperator` in such case.


## Long answer

As documentation point out, this serves as a more general way of putting an in-memory input to DALI pipeline (more general than `fn.external_source`). Such an input operator differs from a Reader, that the reader loads data from disk. Following the `FileReader` example, when it is a `FileReader` you'd need to provide it with all the names of the files beforehand. On the other hand, if it would be a `FileInput`, the execution model would differ slightly - you'd need to provide the `FileInput` with the names of the files by using `feed_input` function, before the `pipeline.run()`, e.g.:
```python
@pipleline_def
def pipe():
    img = fn.inputs.file(name="FILE_INPUT")
    ...

p = pipe(batch_size=...)
p.build()
p.feed_input("FILE_INPUT", my_file_names1)
p.feed_input("FILE_INPUT", my_file_names2)
p.run()
```
The input operator contains an inner queue of the data. That means, that you can call `feed_input` multiple times and the operator will just take whatever it has on the top of the queue.

The real life example of an input operator is the `fn.inputs.video` 
https://github.com/NVIDIA/DALI/blob/ec2756a37bb5628a7a7a8ff8751735b1a9659546/dali/test/python/input/test_video.py#L121

This has been merged today, so it does not have a documentation yet generated on DALI manual page, however it should be there in a day or two. This operator takes an encoded video as a byte-stream (fed by `feed_input`) and returns portions of the decoded video.

Hopefully I've been clear here. Should you have any questions about this, don't hesitate to ask. Just FTR, we might not be replying during the next few days, because of limited availability.

**Comment by fversaci** [comment]
Hi @szalpal ,

thanks a lot for the detailed answer!

I will surely look at the `InputOperator` to see if we can adapt it to match our needs.

Wish you guys happy holidays!

**Comment by fversaci** [comment]
Hi @szalpal ,

Sorry for the late reply, but I have finally managed to implement a first variation of the Cassandra-DALI-plugin which uses the InputOperator (DALI v1.22.0) and it does seem to work so far :)

I have a few doubts though:

1) If I pass the parameter `name="Reader"` to the operator, I see that two DataNodes are created, with names `Reader[0]` and `Reader[1]` and I can use either of them as parameter to `feed_input` for the pipeline to work. Is this correct? Is this related to the operator producing two outputs? In your example there seemed to be just one DataNode, with the same name passed to the InputOperator.

2) I have initially put a `HandleDataAvailability` and a `ForwardCurrentData` in the `SetupImpl` method to see that data were read correctly. From what I understood this automatically produces new data each time `RunImpl` is called, without the need of additional calls. I then modified the code to fill an internal prefetch buffer within my operator and, to get the inputs, I invoke `ForwardCurrentData` multiple time during the first execution of `RunImpl`. Is this the correct approach to access more elements from the underlying CachingList? (It does seem to work: i.e., the input changes...)

3) From what I understood when InputOperator is used sharding must be managed seperately, i.e., one must feed the appropriate inputs to each different (parallely executing) pipeline according to their shard id. Is this correct?

Thanks!

**Comment by JanuszL** [comment]
Hi @fversaci,

Let me answer your questions one by one:
> If I pass the parameter name="Reader" to the operator,

Yes, each output is enumerated separately. Using any of them should work.

> I have initially put a HandleDataAvailability and ...

As we discussed in https://github.com/NVIDIA/DALI/issues/4669, it works as long as provides its own `NextBatchSize` and `Advance` which by default assumes that each iteration consumes only one input batch.

> From what I understood when InputOperator is used sharding must be managed seperately, 

Yes, the InputOperator doesn't manage sharding on its own, although nothing stops you from doing this. I can imagine that you pass the batch ID to it and then based on the number of shards and shard ID it will produce the right sample.

**Comment by fversaci** [comment]
Hi @JanuszL ,

thanks again for the detailed answer. I'll now start working on the sharding part then.

**Comment by fversaci** [comment]
Hi @JanuszL and @szalpal ,

I've updated the Cassandra plugin to support DALI v1.23, implementing the following changes:

1) In `ForwardCurrentData` there's now a new `target_data_id` parameter. From what I understood that allows to tag the data with some custom string, and i just passed a `std::nullopt` to [it](https://github.com/fversaci/cassandra-dali-plugin/blob/inputoperator/crs4/cpp/cassandra_dali.cc#L62).

2) I added the [methods](https://github.com/fversaci/cassandra-dali-plugin/blob/inputoperator/crs4/cpp/cassandra_dali.h#L43) `in_layout`, `in_ndim` and `in_dtype`, to return, respectively `"B"`, `2` and `DALIDataType::DALI_UINT64`. I understood these values are a description of the the input stream (which in our case is made of pairs of uint64, each pair representing a 128-bit UUID) is that correct? Where are these methods used? I tried modifying the return values of `in_dim` and `in_dtype` and the code still executes correctly...

Thanks!

**Comment by szalpal** [comment]
Hello @fversaci !

Let me answer your questions.

ad 1. You're correct, passing `std::nullopt` is fine if you don't need to use special ID for a given input.

ad 2. Currently these values are only available via the C API ([these three functions](https://github.com/NVIDIA/DALI/blob/3c9a0a6527bef5bb9062143bd6b6063385b03287/include/dali/c_api.h#L377)). We're using those in the DALI Backend for Triton. If you're running the pipeline using Python API, the values are not relevant. It's possible they will become relevant though, if we add the type and layout verification during the build stage.

**Comment by fversaci** [comment]
Perfect, thanks for your answers @szalpal !
