### ISSUE TITLE
CUDA compatibility with minor versions?

### ISSUE THREAD

**Issue by thomas-bouvier** [NVIDIA/DALI#4604]
Hello, is this library compatible will all CUDA minor versions? For instance:

- Is `pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/ nvidia-dali-cuda110==1.22.0` compatible with CUDA 11.0, CUDA 11.1, CUDA 11.2.x, CUDA 11.3.x, ..., CUDA 11.8.x
- Will `pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/ nvidia-dali-cuda120==1.22.0` be compatible with CUDA 12.0, CUDQ 12.X, ...

I make sure this is true before I prepare a package for Spack. Thanks!

**Comment by szalpal** [comment]
Hello @thomas-bouvier !

Short answer: yes.

Longer one: we use a [CUDA enhanced compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#enhanced-compat-minor-releases), therefore DALI version entitled `cuda110` also supports all minor versions of CUDA11. On the other hand, it would be the best to have the latest driver version possible, since this may bring some new features to the table.

**Comment by thomas-bouvier** [comment]
Thank you :)
