### ISSUE TITLE
installing a pypi package that had DALI as a dependency 

### ISSUE THREAD

**Issue by danbider** [NVIDIA/DALI#4783]
I want to upload my package to PyPi and allow ppl to `pip install` it. 
I have DALI as a dependency.
currently I have a setup.py file with all other packages, and a requirements.tx file with 
```
--extra-index-url https://developer.download.nvidia.com/compute/redist
nvidia-dali-cuda120

-e .
```
and I ask users to `pip install -r requirements.txt`
is there a way to add dali to my `setup.py` file so that it could all be installed from pypi?

**Comment by JanuszL** [comment]
Hi @danbider,

DALI for cuda120 is fully available through PyPi now - https://pypi.org/project/nvidia-dali-cuda120 and https://pypi.org/project/nvidia-dali-tf-plugin-cuda120.
We are not advertising it yet as want to make sure that our publishing process works smoothly.
However, due to size constrain https://pypi.org/project/nvidia-dali-cuda110 is available only for aarch64 platform.

**Comment by danbider** [comment]
@JanuszL i'm testing the PyPi install on my end, will keep you posted

**Comment by danbider** [comment]
this is working for me, thanks!
