### ISSUE TITLE
should DALI cuda version same as local cuda or pytorch cuda?

### ISSUE THREAD

**Issue by LuoXin-s** [NVIDIA/DALI#4829]
### Describe the question.

Pytorch distributes its package with builtin cuda, so I can use a pytorch with cuda 11.8 even I have cuda 12.0 in local. The question is which cuda version of DALI should I install so it can works correctly with my environments?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @LuoXin-s,

Thank you for your question.
Regarding DALI builds based on CUDA 11, they incorporate necessary CUDA packages and you can use it with any CUDA version on your system as long as you have CUDA 11 capable driver.
When it comes to CUDA 12-based builds, DALI due to size constraints uses the CUDA that is available in the system, still any minor version from 12.x family should work just fine thanks to [CUDA minor version compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#minor-version-compatibility).

**Comment by LuoXin-s** [comment]
Hi @JanuszL , this answer solve my question perfectly, thanks!
