### ISSUE TITLE
Question about CUDA vm resource

### ISSUE THREAD

**Issue by Esthesia** [NVIDIA/DALI#4847]
### Describe the question.

Dear all,

I have 2 questions about calling memory in DALI.
This is the code snippet in the DALI's `cuda_vm_resource.h`
I wonder why DALI decides to set block_size_ to 64MiB.
1. Is there any technical reason to decide this number as a capped number?

```
    if (block_size_ == 0) {
      size_t grain = cuvm::GetAddressGranularity();
      block_size_ = std::max(grain,  // at least grain, for correctness
                             std::min<size_t>(next_pow2(total_mem_ >> 8),  // capacity-dependent...
                                              64 << 20));  // ...but capped at 64 MiB
```

2. I wonder about how the address is translated into hardware.
As far as I understood, CudaMalloc and CudaVM are different like

> VM : virtual_address -- (Map) --> physical_address with fixed granularity
> CudaMalloc: physical_address with coarse granularity
> 
But, the software-side(DALI) physical address needs to translate to the real hardware address.
When and how is it translated?

Both questions are related with that I usually think that page-table translation on GPU using a huge page table (2MiB)
so this raised 2 questions I mentioned above.

Thank you.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by mzient** [comment]
Hello @Esthesia 
Yes, the pages are physically only 2MiB and that's the granularity that's required by CUDA VMM. The "page" size depends on the total GPU size, but the cap on 64MiB is rather arbitrary. In general, smaller pages provide better resilience against fragmentation whereas larger pages allow us to reduce the number of interactions with the OS/driver.

> But, the software-side(DALI) physical address needs to translate to the real hardware address. When and how is it translated?

We don't even see a physical address - it's hidden behind a handle to a cuMem memory block. It's mapped to a virtual address via cuMemMap.
In case of cudaMalloc, the mapping is done by the driver and you get a virtual address.

As for the granularity - cudaMalloc has a finer granularity - the problem is that it's terribly slow, so we cannot use it as an equivalent of `malloc` - and being unmovable, the memory allocated with cudaMalloc isn't well suited for building memory pools, since it causes out-of-memory condition due to fragmentation.

**Comment by Esthesia** [comment]
Hello @mzient,

Thanks for your answer.

> We don't even see a physical address - it's hidden behind a handle to a cuMem memory block. It's mapped to a virtual address via cuMemMap.

So it means that if we create 64MiB using CuMem::Create, then it will create consecutive 2MiB (You said that it depends on GPU, but let's assume 2MiB) x 32 pages?

The other last question is then, if DALI tries to access the memory, is the CUDA device driver in charge of translation to a physical address?

**Comment by mzient** [comment]
> So it means that if we create 64MiB using CuMem::Create, then it will create consecutive 2MiB (You said that it depends on GPU, but let's assume 2MiB) x 32 pages?

From what I understand, the physical pages don't need to be consecutive. That's the beauty of the paging system.

> The other last question is then, if DALI tries to access the memory, is the CUDA device driver in charge of translation to a physical address?

In the end, the memory management unit in the hardware and the operating system are responsible for that. TLB, page tables - the usual stuff.
