### ISSUE TITLE
pip versions

### ISSUE THREAD

**Issue by danbider** [NVIDIA/DALI#4849]
### Describe the question.

@JanuszL,
I want to generalize my `setup.py` installation for users who have different versions of cuda drivers installed. 
Is it recommended to do -- 
* cuda driver 11.x --> `pip install nvidia-dali-cuda-110`
*  cuda driver 12.x --> `pip install nvidia-dali-cuda-120`
We've been working successfully with `nvidia-dali-cuda-120` from pip, for both cuda 12 and cuda 11.8.

Big thanks,
Dan

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @danbider,

Yes, for CUDA 11.x driver please use `nvidia-dali-cuda-110`. For the CUDA 12.x `nvidia-dali-cuda-120`. However the `nvidia-dali-cuda-120` requires the cuda to be installed by the users, either from the wheel or system package manager (we link the CUDA dynamically to shrink the size of the DALI wheel).
Regarding the `nvidia-dali-cuda-110` only aarch64 build is present on PyPi due to size constrain. I just filled a request to increase the size limit https://github.com/pypi/support/issues/2832, so we can post the x86 build there as well.

**Comment by danbider** [comment]
@JanuszL I was able to run lightning-pose tests for dali using `nvidia-dali-cuda-110` from pip on a x86 architecture, not aarch64. Was this your experience too? or should I assume this won't work in general?

**Comment by JanuszL** [comment]
It works because the 1.16 release was below the threshold limit for x86, the more recent ones are not yet available there.
If the 1.16 release is sufficient for your work that is fine, but long term it would be best to allow the users to use the latest release available. I hope the PyPi limit will be extended and we can post official releases there for CUDA 11.x x86_64.

**Comment by danbider** [comment]
awesome, yes, we will not pin down the version, we want the latest releases. please keep us posted when the PyPI limit is extended.

**Comment by JanuszL** [comment]
Feel free to subscribe as a watcher to https://github.com/pypi/support/issues/2832.

**Comment by JanuszL** [comment]
Hi @danbider,

The limit has been extended and DALI 1.26 for CUDA 11.x is available from PyPI.
