### ISSUE TITLE
How exactly does distributing the dataset with DALI/TensorFlow work?

### ISSUE THREAD

**Issue by cyanic-selkie** [NVIDIA/DALI#5171]
### Describe the question.

Hi,

I'm trying to figure out how exactly distributing the dataset works in the context of TensorFlow.

Let's say I have a setup with multiple workers, each having multiple GPUs. The dataset is stored in a number of TFRecords. Using `tf.data.Dataset`, I would simply define the `MultiWorkerMirroredStrategy` and distribute the dataset using `experimental_distribute_dataset`.

From what I understand, in DALI, I have to manually define the shards via the `shard_id` and the `num_shards` parameters of the `fn.readers.tfrecord`. I can't simply use the `experimental_distribute_dataset`? Is there any way I could use it? Perhaps using an `external_source` of `tf.data.TFRecordDataset`? I'm assuming this would cause issues with its automatic batching and prefetching on device?

The example in the documentation for `MirroredStrategy` uses `distribute_datasets_from_function`. Is this only necessary if workers have multiple GPUs, as opposed to each worker having only one? In that case, can I simply pass in the `tf.data.Dataset` to the `fit` function.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @cyanic-selkie,

Thank you for reaching out.
Based on [the `InputContext` documentation](https://www.tensorflow.org/api_docs/python/tf/distribute/InputContext), you can use `num_input_pipelines` and `input_pipeline_id` to determine the number of shards and shard id.
However, I'm not sure if we can reliably extract the local rank from it. So regarding:
> Is this only necessary if workers have multiple GPUs, as opposed to each worker having only one? In that case, can I simply pass in the tf.data.Dataset to the fit function. 

I will defer to @awolant.

**Comment by awolant** [comment]
Hello @cyanic-selkie 

thanks for the questions. I will do my best to answer them. 

> I can't simply use the experimental_distribute_dataset? Is there any way I could use it?

`experimental_distribute_dataset` assumes that  whatever is passed as an argument is a whole dataset. It handles the batching and the sharding. 
One instance of DALI dataset returns already batched outputs for already specified shard. Exactly as you pointed out, applying `experimental_distribute_dataset` for DALI dataset would not be compatible with how DALI operates. 

> The example in the documentation for MirroredStrategy uses distribute_datasets_from_function. Is this only necessary if workers have multiple GPUs, as opposed to each worker having only one?

Due to how `experimental_distribute_dataset` works DALI uses `distribute_datasets_from_function`. As @JanuszL pointed out, this mechanism has access to current rank. We can create an instance of DALI dataset on demand for the current GPU based on `input_context`. So this is necessary always when you have more than one GPU in the training, not only when you have multiple GPUs per machine. Basically, you need to somehow tell DALI which shard should be returned by a dataset instance.

`MultiWorkerMirroredStrategy` supports `distribute_datasets_from_function`. So theoretically, you could use that.

Unfortunately, this code path does not support all necessary options. The problem is that for DALI support, some additional experimental code was added in TF internals, especially, `experimental_place_dataset_on_device`. And this only works for 

```
input_options = tf.distribute.InputOptions(
    experimental_place_dataset_on_device = True,
    experimental_fetch_to_device = False,
    experimental_replication_mode = tf.distribute.InputReplicationMode.PER_WORKER)
```

as in the tutorial: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/tensorflow/tensorflow-dataset-multigpu.html. 
These options are what forces the TF to process the dataset in a way that does not interfere with the GPU-to-GPU copy mechanism. Without it, it is probable that even though DALI dataset will produce the output on the GPU this output will be unnecessarily pulled to the CPU. 
So, in this tutorial you can replace `MirroredStrategy` with `MultiWorkerMirroredStrategy`, remove the `input_options` and the code will run, probably with this additional copy.

> In that case, can I simply pass in the tf.data.Dataset to the fit function.

Depending on your exact setup this might work as intended, although we never tried it like this. The key is to know the rank of current process and configure the `fit` function in a way that would be compatible with what DALI dataset returns (mostly shape of the output). 
 You would have to check if it suffers the same issues with GPU prefetching or not.

Something else to try out might be `horovod`: https://github.com/horovod/horovod  It can replace the `tf.distributed` as a tool to spread the training to multiple workers. In this setup, something similar to passing DALI dataset to `fit` used to work.

**Comment by cyanic-selkie** [comment]
Thank you for the detail response, @awolant
