### ISSUE TITLE
Error while make install

### ISSUE THREAD

**Issue by JiangPQ** [NVIDIA/DALI#7]
> [ 77%] Linking CXX shared library libdali.so
**/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC**
/usr/lib/x86_64-linux-gnu/libturbojpeg.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
dali/CMakeFiles/dali.dir/build.make:2394: recipe for target 'dali/libdali.so' failed
make[2]: *** [dali/libdali.so] Error 1
CMakeFiles/Makefile2:340: recipe for target 'dali/CMakeFiles/dali.dir/all' failed
make[1]: *** [dali/CMakeFiles/dali.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

The error occurs when I run `make -j4 install`.
What does this mean and how could I fix this?

**Comment by JanuszL** [comment]
Hi,
It looks like it tries to link against libturbojpeg.a statically, what is strange as it should use it as a shared lib.
Please run:
_make VERBOSE=1_
and provide us full link command which is used.
Other question is what version of libturbojpeg do you use? Did you build on your own? If so what options did you use (please look to https://github.com/NVIDIA/DALI/blob/master/Dockerfile.deps to see how we build it).

**Comment by cliffwoolley** [comment]
I suspect this means that the installed libturbojpeg was built only as a static library; cmake might detect libturbojpeg.a in place of libturbojpeg.so if the latter is missing?  (Though I didn't think so based on https://github.com/NVIDIA/DALI/blob/master/cmake/modules/FindJpegTurbo.cmake#L22 .)  If it does, this isn't necessarily super desirable; we prefer dynamically linking to libturbojpeg due to the way it interacts with the libjpeg bundled into OpenCV.
