### ISSUE TITLE
Performance degradation after few iterations on ImageNet

### ISSUE THREAD

**Issue by CosimoRulli** [NVIDIA/DALI#839]
I am trying to train Alexnet on Imagenet, expoliting this code  https://github.com/NVIDIA/DALI/blob/master/docs/examples/pytorch/resnet50/main.py.

At the beginning, data loading is very fast (~1500 img/sec). Afer about 500 epochs, the speed suddenly goes down. I tried different configurations, varying the number of workers, the pytorch  (1.0.0, 1.0.1) and the cuda versions (9.0), but I was not able to find a solution. This happens both with dali_cpu and dali_gpu options.
![train_alexnet_dali](https://user-images.githubusercontent.com/44570600/57089393-a4947400-6d04-11e9-881e-ee7e8326f34b.png)

Can you help me with this problem please?

I'm using DALI 0.8.0, pytorch 1.1.0, cuda 10 on Ubuntu 16.04, on a machine with 8 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 64Gb Ram and a GTX 1080 with 8GB.

**Comment by JanuszL** [comment]
Hi,
I can guess it is due to read access speed from your drive. I guess you are not using SSD or RAID to store your training data. To verify this you can just run nvidia-smi to see GPU utilization and top/htop/any other system monitor to see CPU and IO utilization.
This high speed at the begging is due to caching, as your OS is keeping data read from disk in RAM so when you read them again it already there. But it cannot store all of it (your RAM is not big enough or you are reading data for the first time). In that case, DALI cannot do much as it is about processing while reading data from dick is up to HW you have.

**Comment by CosimoRulli** [comment]
This must be the reason, thank you very much!

**Comment by bhr001** [comment]
@JanuszL ，i check my ram utilization,find there still left free Mem,but speed keep going down,it confuse me

**Comment by JanuszL** [comment]
@bhr001 - I recommend to check https://www.linuxatemyram.com/play.html and use `free -m` command to see real RAM and buff/cache utilization. When you run top/htop it shows memory not allocated by the applications, while dick caches are not shown there (as it is a memory that could be released by the OS when any app need it).
